### ISSUE TITLE
Unable to start wiki.js with SQLite in Node.js 12 by default

### ISSUE THREAD

**Issue by lawrenceching** [Requarks/wiki#1048]
**Describe the bug**
I was not able to launch wiki.js with SQLite in Node.js 12.

```
wiki-js node server                        
Loading configuration from /Users/<username>/Downloads/tmp/wiki-js/config.yml... OK
2019-09-18T13:45:12.637Z [MASTER] info: =======================================
2019-09-18T13:45:12.640Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-09-18T13:45:12.640Z [MASTER] info: =======================================
2019-09-18T13:45:12.640Z [MASTER] info: Initializing...
Knex: run
$ npm install sqlite3 --save
Cannot find module '/Users/<username>/Downloads/tmp/wiki-js/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/sqlite3/lib/sqlite3.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/knex.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/index.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/knex.js
- /Users/<username>/Downloads/tmp/wiki-js/server/core/db.js
- /Users/<username>/Downloads/tmp/wiki-js/server/core/kernel.js
- /Users/<username>/Downloads/tmp/wiki-js/server/index.js
Error: Cannot find module '/Users/<username>/Downloads/tmp/wiki-js/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/sqlite3/lib/sqlite3.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/knex.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/index.js
- /Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/knex.js
- /Users/<username>/Downloads/tmp/wiki-js/server/core/db.js
- /Users/<username>/Downloads/tmp/wiki-js/server/core/kernel.js
- /Users/<username>/Downloads/tmp/wiki-js/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/<username>/Downloads/tmp/wiki-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Client_SQLite3._driver (/Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/dialects/sqlite3/index.js:36:12)
    at Client_SQLite3.initializeDriver (/Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/client.js:221:26)
    at Client_SQLite3.Client (/Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/client.js:59:10)
    at new Client_SQLite3 (/Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/dialects/sqlite3/index.js:18:10)
    at Knex (/Users/<username>/Downloads/tmp/wiki-js/node_modules/knex/lib/knex.js:52:28)
(node:9378) UnhandledPromiseRejectionWarning: Error: Knex: run
```

**To Reproduce**
1. Create a blank SQLite file
2. create/update config.yml with below content

```
db:
  type: sqlite
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  #host: localhost
  # port: 5432
  # user: wikijs
  # pass: wikijsrocks
  # db: wiki
  # ssl: false
  # SQLite only:
  storage: /Users/<username>/Downloads/wiki.db
```

Follow the instruction for macOS to start up wiki.js
https://docs.requarks.io/en/install/macos

**Expected behavior**
I can launch wiki.js successfully

**Screenshots**
No

**Host Info (please complete the following information):**
 - OS: macOS 10.14.6 (18G95)
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: SQLite 3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl
 - Node.js: v12.10.0
 - npm: 6.11.3

**Additional context**
No.

**Comment by lawrenceching** [comment]
I don't know Node.js very well.
But I found a solution by myself in this page:
https://github.com/mapbox/node-sqlite3/issues/906

I started up wiki.js successfully after I ran `npm rebuild`.

If it's expected behavior, I think it would better to supplement this step in https://docs.requarks.io/en/install/macos.

**Comment by NGPixel** [comment]
Added in the macOS docs.

**Comment by hashworks** [comment]
Note that this step is needed on linux as well if one wants to use sqlite, so it should also be added on [its wiki page](https://docs.requarks.io/en/install/linux).
