### ISSUE TITLE
First run failed - Fetching latest updates from Graph endpoint

### ISSUE THREAD

**Issue by Steve-Mcl** [Requarks/wiki#1064]
**Host Info**
OS: Windows 10
Wiki.js version: 2.0.0-beta.303
Database engine: sqlite

On first run, the application fails with the below error.

This may be related to proxy however I CAN open https://graph.requarks.io/ in the browser on the same machine.

Is there a workaround - i.e. can files be manually downloaded and place into installation folder?

Would greatly appreciate some assistance as I wish to evaluate WikiJS as a replacement for our aged screwturn wiki.

Thanks Steve.

**First run log...**
```
2019-09-26T10:27:12.458Z [MASTER] info: =======================================
2019-09-26T10:27:12.464Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-09-26T10:27:12.465Z [MASTER] info: =======================================
2019-09-26T10:27:12.466Z [MASTER] info: Initializing...
2019-09-26T10:27:13.220Z [MASTER] info: Connecting to database...
2019-09-26T10:27:13.748Z [MASTER] info: Database Connection Successful [ OK ]
2019-09-26T10:27:14.554Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-09-26T10:27:14.557Z [MASTER] info: Starting setup wizard...
2019-09-26T10:27:15.353Z [MASTER] info: Starting HTTP server on port 3000...
2019-09-26T10:27:15.355Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-26T10:27:15.376Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-09-26T10:27:15.379Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-09-26T10:27:15.381Z [MASTER] info:
2019-09-26T10:27:15.383Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-09-26T10:27:15.383Z [MASTER] info:
2019-09-26T10:27:15.383Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-09-26T10:28:07.084Z [MASTER] info: Creating data directories...
2019-09-26T10:28:07.110Z [MASTER] info: Generating certificates...
2019-09-26T10:28:07.659Z [MASTER] info: Persisting config to DB...
2019-09-26T10:28:11.549Z [MASTER] info: Installing default locale...
2019-09-26T10:28:12.596Z [MASTER] info: Creating default groups...
2019-09-26T10:28:14.158Z [MASTER] info: Loaded 20 new authentication strategies: [ OK ]
2019-09-26T10:28:15.863Z [MASTER] info: Loaded 3 new editors: [ OK ]
2019-09-26T10:28:17.409Z [MASTER] info: Loaded 12 new loggers: [ OK ]
2019-09-26T10:28:18.111Z [MASTER] info: Loaded 19 new renderers: [ OK ]
2019-09-26T10:28:19.018Z [MASTER] info: Loaded 9 new search engines: [ OK ]
2019-09-26T10:28:21.533Z [MASTER] info: Loaded 10 new storage targets: [ OK ]
2019-09-26T10:28:21.535Z [MASTER] info: Creating root administrator...
2019-09-26T10:28:23.239Z [MASTER] info: Creating guest account...
2019-09-26T10:28:23.847Z [MASTER] info: Creating default site navigation
2019-09-26T10:28:24.332Z [MASTER] info: Setup is complete!
2019-09-26T10:28:24.336Z [MASTER] info: Stopping Setup...
2019-09-26T10:28:24.338Z [MASTER] info: Setup stopped. Starting Wiki.js...
2019-09-26T10:28:28.805Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
2019-09-26T10:28:29.657Z [MASTER] info: Loading GraphQL Schema...
2019-09-26T10:28:32.175Z [MASTER] info: GraphQL Schema: [ OK ]
2019-09-26T10:28:32.747Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-26T10:28:32.910Z [MASTER] info: HTTP Server: [ RUNNING ]
TypeError: C:\wiki\server\views\master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (C:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (C:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:151:139)
    at Object.exports.renderFile (C:\wiki\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (C:\wiki\node_modules\pug\lib\index.js:417:21)
    at View.exports.__express [as engine] (C:\wiki\node_modules\pug\lib\index.js:464:11)
    at View.render (C:\wiki\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\wiki\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\wiki\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\wiki\node_modules\express\lib\response.js:1012:7)
    at app.use (C:\wiki\server\master.js:178:9)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
    at C:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (C:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
    at C:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (C:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
TypeError: C:\wiki\server\views\master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (C:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (C:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:151:139)
    at Object.exports.renderFile (C:\wiki\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (C:\wiki\node_modules\pug\lib\index.js:417:21)
    at View.exports.__express [as engine] (C:\wiki\node_modules\pug\lib\index.js:464:11)
    at View.render (C:\wiki\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\wiki\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\wiki\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\wiki\node_modules\express\lib\response.js:1012:7)
    at app.use (C:\wiki\server\master.js:178:9)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
    at C:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (C:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
    at C:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (C:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\wiki\node_modules\express\lib\router\index.js:315:13)
```

**Comment by Steve-Mcl** [comment]
I have manged to get passed this point on the next run (although errors did still occur) however the site obviously has no language files as everything is like this....


![image](https://user-images.githubusercontent.com/44235289/65684588-e3cab500-e057-11e9-86fe-2ab0b80b72d5.png)


Again, any help getting going (short of routing an open internet connection through corporate env to this Win10 VM) would be appreciated.

**Comment by Steve-Mcl** [comment]
Hi & thanks for the reply.

I followed the sideload instructions (placed files in \data\sideload) & restarted `node server`...
![image](https://user-images.githubusercontent.com/44235289/65691203-5ba0db80-e068-11e9-96fe-acbd3e0df670.png)


Still get error on startup... 
![image](https://user-images.githubusercontent.com/44235289/65691404-ade1fc80-e068-11e9-86a5-894c0bce3961.png)


And yet I can still access https://graph.requarks.io/...
![image](https://user-images.githubusercontent.com/44235289/65691485-d0741580-e068-11e9-98b6-ec929b636722.png)


And still no languages (I have done hard refresh)...
![image](https://user-images.githubusercontent.com/44235289/65691249-6fe4d880-e068-11e9-97b2-b4549b7d1488.png)

Did I miss something?

Please help me get this resolved.

Many thanks, Steve.

**Comment by NGPixel** [comment]
Have you set offline to true in your config file?

https://github.com/Requarks/wiki/blob/7b46d2a4fc4f15ec7c6dbf400d9e7504083d78cf/config.sample.yml#L115

**Comment by Steve-Mcl** [comment]
How did I miss that.

My apologies - its now gets past the errors. 

NOTE: I still have no language on web (still shows welcome.title & welcome.subtitle etc) (even after hard refresh of browser)

I will delete DB & re-do the initialisation bit - see if that helps.

**Comment by Steve-Mcl** [comment]
ok, so this is what happens now...

1. Deleted db
2. Ensured .json files in \data\sideload\
3. Ensured ` offline: false` in `config.yml`
4. `node server`

**Results...**
 ```
Loading configuration from c:\wiki\config.yml... OK
2019-09-26T13:32:28.417Z [MASTER] info: =======================================
2019-09-26T13:32:28.423Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-09-26T13:32:28.423Z [MASTER] info: =======================================
2019-09-26T13:32:28.424Z [MASTER] info: Initializing...
2019-09-26T13:32:29.197Z [MASTER] info: Connecting to database...
2019-09-26T13:32:29.224Z [MASTER] info: Database Connection Successful [ OK ]
2019-09-26T13:32:29.554Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-09-26T13:32:29.557Z [MASTER] info: Starting setup wizard...
2019-09-26T13:32:29.882Z [MASTER] info: Starting HTTP server on port 3000...
2019-09-26T13:32:29.885Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-26T13:32:29.904Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-09-26T13:32:29.907Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-09-26T13:32:29.908Z [MASTER] info:
2019-09-26T13:32:29.909Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-09-26T13:32:29.909Z [MASTER] info:
2019-09-26T13:32:29.910Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-09-26T13:33:07.065Z [MASTER] info: Creating data directories...
2019-09-26T13:33:07.071Z [MASTER] info: Generating certificates...
2019-09-26T13:33:07.147Z [MASTER] info: Persisting config to DB...
2019-09-26T13:33:07.942Z [MASTER] info: Installing default locale...
2019-09-26T13:33:07.989Z [MASTER] info: Creating default groups...
2019-09-26T13:33:08.254Z [MASTER] info: Loaded 20 new authentication strategies: [ OK ]
2019-09-26T13:33:08.364Z [MASTER] info: Loaded 3 new editors: [ OK ]
2019-09-26T13:33:08.489Z [MASTER] info: Loaded 12 new loggers: [ OK ]
2019-09-26T13:33:08.582Z [MASTER] info: Loaded 19 new renderers: [ OK ]
2019-09-26T13:33:08.660Z [MASTER] info: Loaded 9 new search engines: [ OK ]
2019-09-26T13:33:08.785Z [MASTER] info: Loaded 10 new storage targets: [ OK ]
2019-09-26T13:33:08.788Z [MASTER] info: Creating root administrator...
2019-09-26T13:33:09.458Z [MASTER] info: Creating guest account...
2019-09-26T13:33:09.552Z [MASTER] info: Creating default site navigation
2019-09-26T13:33:09.614Z [MASTER] info: Setup is complete!
2019-09-26T13:33:09.618Z [MASTER] info: Stopping Setup...
2019-09-26T13:33:09.621Z [MASTER] info: Setup stopped. Starting Wiki.js...
2019-09-26T13:33:11.442Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
2019-09-26T13:33:11.768Z [MASTER] info: Loading GraphQL Schema...
2019-09-26T13:33:12.153Z [MASTER] info: GraphQL Schema: [ OK ]
2019-09-26T13:33:12.444Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-26T13:33:12.495Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-09-26T13:33:12.501Z [MASTER] info: Sideload directory detected. Looking for packages...
2019-09-26T13:33:12.518Z [MASTER] info: Found locales master file. Importing locale packages...
2019-09-26T13:33:12.545Z [MASTER] info: Importing Arabic locale package...
2019-09-26T13:33:12.801Z [MASTER] info: Loaded 12 new analytics providers: [ OK ]
2019-09-26T13:33:12.851Z [MASTER] info: Importing Bulgarian locale package...
2019-09-26T13:33:12.899Z [MASTER] info: Importing Chinese Simplified locale package...
TypeError: c:\wiki\server\views\master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (c:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (c:\wiki\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:151:139)
    at Object.exports.renderFile (c:\wiki\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (c:\wiki\node_modules\pug\lib\index.js:417:21)
    at View.exports.__express [as engine] (c:\wiki\node_modules\pug\lib\index.js:464:11)
    at View.render (c:\wiki\node_modules\express\lib\view.js:135:8)
    at tryRender (c:\wiki\node_modules\express\lib\application.js:640:10)
    at Function.render (c:\wiki\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (c:\wiki\node_modules\express\lib\response.js:1012:7)
    at app.use (c:\wiki\server\master.js:178:9)
    at Layer.handle_error (c:\wiki\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (c:\wiki\node_modules\express\lib\router\index.js:315:13)
    at c:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (c:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (c:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (c:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (c:\wiki\node_modules\express\lib\router\index.js:315:13)
    at c:\wiki\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (c:\wiki\node_modules\express\lib\router\index.js:335:12)
    at next (c:\wiki\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (c:\wiki\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (c:\wiki\node_modules\express\lib\router\index.js:315:13)
2019-09-26T13:33:13.074Z [MASTER] info: Importing Chinese Traditional locale package...
2019-09-26T13:33:13.149Z [MASTER] info: Importing Czech locale package...
2019-09-26T13:33:13.209Z [MASTER] info: Importing Danish locale package...
2019-09-26T13:33:13.258Z [MASTER] info: Importing Dutch locale package...
2019-09-26T13:33:13.339Z [MASTER] info: Importing English locale package...
2019-09-26T13:33:13.414Z [MASTER] info: Importing Estonian  locale package...
2019-09-26T13:33:13.425Z [MASTER] info: No new authentication strategies found: [ SKIPPED ]
2019-09-26T13:33:13.478Z [MASTER] info: Importing French locale package...
2019-09-26T13:33:13.540Z [MASTER] info: Importing German locale package...
2019-09-26T13:33:13.553Z [MASTER] info: No new editors found: [ SKIPPED ]
2019-09-26T13:33:13.615Z [MASTER] info: Importing Greek locale package...
2019-09-26T13:33:13.664Z [MASTER] info: Importing Hebrew locale package...
2019-09-26T13:33:13.727Z [MASTER] info: Importing Hungarian locale package...
2019-09-26T13:33:13.789Z [MASTER] info: Importing Italian locale package...
2019-09-26T13:33:13.852Z [MASTER] info: Importing Japanese locale package...
2019-09-26T13:33:13.867Z [MASTER] info: No new loggers found: [ SKIPPED ]
2019-09-26T13:33:13.915Z [MASTER] info: Importing Korean locale package...
2019-09-26T13:33:13.977Z [MASTER] info: Importing Lithuanian locale package...
2019-09-26T13:33:14.040Z [MASTER] info: Importing Persian locale package...
2019-09-26T13:33:14.103Z [MASTER] info: Importing Polish locale package...
2019-09-26T13:33:14.168Z [MASTER] info: Importing Portuguese locale package...
2019-09-26T13:33:14.227Z [MASTER] info: Importing Portuguese (Brazil) locale package...
2019-09-26T13:33:14.289Z [MASTER] info: Importing Romanian locale package...
2019-09-26T13:33:14.350Z [MASTER] info: No new renderers found: [ SKIPPED ]
2019-09-26T13:33:14.356Z [MASTER] info: Importing Russian locale package...
2019-09-26T13:33:14.414Z [MASTER] info: Importing Slovak locale package...
2019-09-26T13:33:14.474Z [MASTER] info: Importing Slovenian (Slovenia) locale package...
2019-09-26T13:33:14.524Z [MASTER] info: Importing Spanish locale package...
2019-09-26T13:33:14.584Z [MASTER] info: No new search engines found: [ SKIPPED ]
2019-09-26T13:33:14.588Z [MASTER] info: Importing Swedish locale package...
2019-09-26T13:33:14.646Z [MASTER] info: Importing Turkish locale package...
2019-09-26T13:33:14.696Z [MASTER] info: Importing Ukrainian locale package...
2019-09-26T13:33:14.758Z [MASTER] info: Importing Vietnamese locale package...
2019-09-26T13:33:14.818Z [MASTER] info: Imported 31 locale packages: [COMPLETED]
2019-09-26T13:33:14.838Z [MASTER] info: No new storage targets found: [ SKIPPED ]
2019-09-26T13:33:14.849Z [MASTER] info: Authentication Strategy local: [ OK ]
2019-09-26T13:33:14.860Z [MASTER] info: Purging orphaned upload files...
2019-09-26T13:33:14.861Z [MASTER] warn: Skipping job syncGraphLocales because offline mode is enabled. [SKIPPED]
2019-09-26T13:33:14.862Z [MASTER] warn: Skipping job syncGraphUpdates because offline mode is enabled. [SKIPPED]
2019-09-26T13:33:14.864Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
```

Web pages initially showed the initial "enter username and password" then the page flipped to this error...
![image](https://user-images.githubusercontent.com/44235289/65692762-0dd9a280-e06b-11e9-9bd3-8eab443b115d.png)

Sorry for the hassle

**Comment by Steve-Mcl** [comment]
For anyone reading this - I redid the whole thing.

1. Follow this [guide](https://docs.requarks.io/en/install/windows) (but DO NOT RUN!)
1. Edit config (notepad .\config.yml)
   1. set `offline: false' 
1. Sideload [language files](https://docs.requarks.io/en/install/sideload)
1. start up `node server`

**Comment by coamtaker618** [comment]
The proposed solution did not work for me. I cloned the files in the "data/sideload/" folder AND 

Please note that I am using mariadb & Ubuntu Server 18.04 LTS...but I do not believe these changes are relevant to this issue.
