### ISSUE TITLE
 First run failed - Cannot read property 'lang' of undefined

### ISSUE THREAD

**Issue by coamtaker618** [Requarks/wiki#1075]
The bug is an exact duplicate of issue #1064 but the proposed solution did not work.

Please not that my setup is different, but the problem appears to be the same:
OS: Ubuntu Server 18.03 LTS
Wiki.js version: 2.0.0-beta.303
Database engine: mariadb

As with issue #1064 I am able to start with "node server" and see the welcome page requesting email & password.  After those are submitted, the error occurs:

Debug Log:
2019-09-28T18:11:19.820Z [MASTER] info: =======================================
2019-09-28T18:11:19.824Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-09-28T18:11:19.825Z [MASTER] info: =======================================
2019-09-28T18:11:19.825Z [MASTER] info: Initializing...
2019-09-28T18:11:20.416Z [MASTER] info: Connecting to database...
2019-09-28T18:11:20.464Z [MASTER] info: Database Connection Successful [ OK ]
2019-09-28T18:11:28.879Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-09-28T18:11:28.880Z [MASTER] info: Starting setup wizard...
2019-09-28T18:11:29.334Z [MASTER] info: Starting HTTP server on port 3000...
2019-09-28T18:11:29.335Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-28T18:11:29.352Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-09-28T18:11:29.353Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-09-28T18:11:29.353Z [MASTER] info:
2019-09-28T18:11:29.354Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-09-28T18:11:29.354Z [MASTER] info:
2019-09-28T18:11:29.355Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-09-28T18:11:45.950Z [MASTER] info: Creating data directories...
2019-09-28T18:11:45.993Z [MASTER] info: Generating certificates...
2019-09-28T18:11:46.264Z [MASTER] info: Persisting config to DB...
2019-09-28T18:11:46.706Z [MASTER] info: Installing default locale...
2019-09-28T18:11:46.732Z [MASTER] info: Creating default groups...
2019-09-28T18:11:46.966Z [MASTER] info: Loaded 20 new authentication strategies: [ OK ]
2019-09-28T18:11:47.017Z [MASTER] info: Loaded 3 new editors: [ OK ]
2019-09-28T18:11:47.110Z [MASTER] info: Loaded 12 new loggers: [ OK ]
2019-09-28T18:11:47.233Z [MASTER] info: Loaded 19 new renderers: [ OK ]
2019-09-28T18:11:47.328Z [MASTER] info: Loaded 9 new search engines: [ OK ]
2019-09-28T18:11:47.447Z [MASTER] info: Loaded 10 new storage targets: [ OK ]
2019-09-28T18:11:47.448Z [MASTER] info: Creating root administrator...
2019-09-28T18:11:48.342Z [MASTER] info: Creating guest account...
2019-09-28T18:11:48.366Z [MASTER] info: Creating default site navigation
2019-09-28T18:11:48.382Z [MASTER] info: Setup is complete!
2019-09-28T18:11:48.383Z [MASTER] info: Stopping Setup...
2019-09-28T18:11:48.387Z [MASTER] info: Setup stopped. Starting Wiki.js...
2019-09-28T18:11:50.111Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
2019-09-28T18:11:50.435Z [MASTER] info: Loading GraphQL Schema...
2019-09-28T18:11:50.687Z [MASTER] info: GraphQL Schema: [ OK ]
2019-09-28T18:11:51.080Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-09-28T18:11:51.106Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-09-28T18:11:51.243Z [MASTER] info: Loaded 12 new analytics providers: [ OK ]
2019-09-28T18:11:51.426Z [MASTER] info: No new authentication strategies found: [ SKIPPED ]
2019-09-28T18:11:51.441Z [MASTER] info: No new editors found: [ SKIPPED ]
TypeError: /home/server/wiki/server/views/master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (/home/server/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (/home/server/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:151:139)
    at Object.exports.renderFile (/home/server/wiki/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/server/wiki/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/server/wiki/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/server/wiki/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/server/wiki/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/server/wiki/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/server/wiki/node_modules/express/lib/response.js:1012:7)
    at app.use (/home/server/wiki/server/master.js:178:9)
    at Layer.handle_error (/home/server/wiki/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/server/wiki/node_modules/express/lib/router/index.js:315:13)
    at /home/server/wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/server/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/server/wiki/node_modules/express/lib/router/index.js:315:13)
    at /home/server/wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/server/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/server/wiki/node_modules/express/lib/router/index.js:315:13)
2019-09-28T18:11:51.661Z [MASTER] info: No new loggers found: [ SKIPPED ]
2019-09-28T18:11:51.728Z [MASTER] info: No new renderers found: [ SKIPPED ]
2019-09-28T18:11:51.784Z [MASTER] info: No new search engines found: [ SKIPPED ]
2019-09-28T18:11:51.838Z [MASTER] info: No new storage targets found: [ SKIPPED ]
2019-09-28T18:11:51.852Z [MASTER] info: Authentication Strategy local: [ OK ]
2019-09-28T18:11:51.865Z [MASTER] info: Purging orphaned upload files...
2019-09-28T18:11:51.876Z [MASTER] info: Syncing locales with Graph endpoint...
2019-09-28T18:11:51.878Z [MASTER] info: Fetching latest updates from Graph endpoint...
2019-09-28T18:11:51.890Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
2019-09-28T18:11:52.030Z [MASTER] info: Fetching latest updates from Graph endpoint: [ COMPLETED ]
2019-09-28T18:11:52.204Z [MASTER] info: Pulled latest locale updates for English from Graph endpoint: [ COMPLETED ]
2019-09-28T18:11:52.214Z [MASTER] info: Syncing locales with Graph endpoint: [ COMPLETED ]
2019-09-28T18:13:55.634Z [MASTER] warn: Unable to send analytics telemetry request.
2019-09-28T18:13:57.680Z [MASTER] warn: Unable to send analytics telemetry request.
2019-09-28T18:14:01.776Z [MASTER] warn: Unable to send analytics telemetry request.

**Comment by NGPixel** [comment]
You can ignore this error. It has no impact and will be fixed in an upcoming release.

**Comment by coamtaker618** [comment]
thanks for the reply NGPixel.  While I appreciate that this is already being fixed, I strongly disagree with "it has no impact"  after this occurs nodejs crashes upon saying:

2019-09-28T18:25:16.662Z [MASTER] error: CRITICAL ERROR: Guest user is missing!

I can restart node js with "node server" and get the same error if I am quick or merely a webpage failing to load if I am not quick.

Either way, I am unable to proceed with installation and setup beyond this point.

**Comment by NGPixel** [comment]
The issue title and logs you posted were only about the `Cannot read property 'lang' of undefined` error which is completely unrelated to the guest user missing error (which will be addressed in the next release).

In the meantime, you'll need to edit the guest user row in the users table of your database and make sure it has ID 2.

**Comment by coamtaker618** [comment]
regarding the error in the log (mentioned above):
2019-09-28T18:25:16.662Z [MASTER] error: CRITICAL ERROR: Guest user is missing!

I created a user as requested (email & password) and when I look at the database I see two users:
1) The user I created
2) a guest user "guest@example.com" who isSystem & has no password

**Comment by coamtaker618** [comment]
Awesome, thanks NGPixel. That was exactly it! For some reason my user had ID 1 & the guest had ID 3 (not 2).  I am now creating my first page :)

Also, as I'm obviously totally new to this wiki. It seems that the guest account is unusable if the password is blank. Is this intended?

**Comment by NGPixel** [comment]
The guest user is not supposed to have a password, as you're not going to login with it. The guest user represents any user that is not logged in.

**Comment by coamtaker618** [comment]
Ok, gotcha. Thanks again :)
