### ISSUE TITLE
Issues with localization

### ISSUE THREAD

**Issue by d-kononov** [Requarks/wiki#1203]
**Describe the bug**
Wiki.js has been deployed in k8s cluster and there are some issues with localization (see screenshot).
I don't think it is related to k8s deployment.
Also there are some errors in log:
```
2019-11-09T12:00:42.273Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ]
2019-11-09T12:00:42.274Z [MASTER] error: Cannot read property 'isRTL' of undefined
```

**Screenshots**
<img width="1895" alt="image" src="https://user-images.githubusercontent.com/1768345/68528374-108f0f00-031c-11ea-871e-5fe1d73d0aa3.png">
Locale dropdown is empty.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.0-rc.17 (beta tag)
 - Database engine: postgres 11.4

**Additional information**
I tried to use `dev` tag (docker image), got the same issue.
Logs:
```
Loading configuration from /wiki/config.yml... OK
2019-11-09T12:21:04.957Z [MASTER] info: =======================================
2019-11-09T12:21:04.959Z [MASTER] info: = Wiki.js 2.0.0-rc.17 =================
2019-11-09T12:21:04.959Z [MASTER] info: =======================================
2019-11-09T12:21:04.959Z [MASTER] info: Initializing...
2019-11-09T12:21:06.563Z [MASTER] info: Connecting to database...
2019-11-09T12:21:06.626Z [MASTER] info: Database Connection Successful [ OK ]
2019-11-09T12:21:07.265Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-11-09T12:21:07.266Z [MASTER] info: Starting setup wizard...
2019-11-09T12:21:08.317Z [MASTER] info: Starting HTTP server on port 3000...
2019-11-09T12:21:08.317Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-11-09T12:21:08.324Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-11-09T12:21:08.403Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-11-09T12:21:08.403Z [MASTER] info:
2019-11-09T12:21:08.403Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-11-09T12:21:08.403Z [MASTER] info:
2019-11-09T12:21:08.403Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-11-09T12:21:51.526Z [MASTER] info: Creating data directories...
2019-11-09T12:21:51.609Z [MASTER] info: Generating certificates...
2019-11-09T12:21:51.804Z [MASTER] info: Persisting config to DB...
2019-11-09T12:21:52.456Z [MASTER] info: Installing default locale...
2019-11-09T12:21:52.463Z [MASTER] info: Creating default groups...
2019-11-09T12:21:53.111Z [MASTER] info: Loaded 20 new authentication strategies: [ OK ]
2019-11-09T12:21:53.206Z [MASTER] info: Loaded 4 new editors: [ OK ]
2019-11-09T12:21:53.909Z [MASTER] info: Loaded 12 new loggers: [ OK ]
2019-11-09T12:21:54.109Z [MASTER] info: Loaded 20 new renderers: [ OK ]
2019-11-09T12:21:54.230Z [MASTER] info: Loaded 9 new search engines: [ OK ]
2019-11-09T12:21:54.412Z [MASTER] info: Loaded 10 new storage targets: [ OK ]
2019-11-09T12:21:54.412Z [MASTER] info: Creating root administrator...
2019-11-09T12:21:56.222Z [MASTER] info: Creating guest account...
2019-11-09T12:21:56.227Z [MASTER] info: Creating default site navigation
2019-11-09T12:21:56.304Z [MASTER] info: Setup is complete!
2019-11-09T12:21:56.306Z [MASTER] info: Stopping Setup...
2019-11-09T12:21:56.307Z [MASTER] info: Setup stopped. Starting Wiki.js...
2019-11-09T12:21:59.093Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
2019-11-09T12:21:59.461Z [MASTER] info: Loading GraphQL Schema...
2019-11-09T12:22:00.118Z [MASTER] info: GraphQL Schema: [ OK ]
2019-11-09T12:22:01.506Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-11-09T12:22:01.733Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-11-09T12:22:02.003Z [MASTER] info: Loaded 13 new analytics providers: [ OK ]
2019-11-09T12:22:02.131Z [MASTER] info: No new authentication strategies found: [ SKIPPED ]
2019-11-09T12:22:02.216Z [MASTER] info: No new editors found: [ SKIPPED ]
2019-11-09T12:22:02.319Z [MASTER] info: No new loggers found: [ SKIPPED ]
2019-11-09T12:22:03.106Z [MASTER] info: No new renderers found: [ SKIPPED ]
TypeError: /wiki/server/views/master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:117:139)
    at Object.exports.renderFile (/wiki/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/wiki/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/wiki/node_modules/pug/lib/index.js:464:11)
    at View.render (/wiki/node_modules/express/lib/view.js:135:8)
    at tryRender (/wiki/node_modules/express/lib/application.js:640:10)
    at Function.render (/wiki/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/wiki/node_modules/express/lib/response.js:1012:7)
    at app.use (/wiki/server/master.js:178:9)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
    at /wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
    at /wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
2019-11-09T12:22:03.204Z [MASTER] info: No new search engines found: [ SKIPPED ]
2019-11-09T12:22:03.232Z [MASTER] info: No new storage targets found: [ SKIPPED ]
2019-11-09T12:22:03.308Z [MASTER] info: Authentication Strategy local: [ OK ]
2019-11-09T12:22:03.327Z [MASTER] info: Purging orphaned upload files...
2019-11-09T12:22:03.364Z [MASTER] info: Syncing locales with Graph endpoint...
2019-11-09T12:22:03.604Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
Loading configuration from /wiki/config.yml... OK
2019-11-09T12:22:04.810Z [JOB] info: Rebuilding page tree...
2019-11-09T12:22:06.224Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
```

**Comment by terrymunro** [comment]
Not sure if this is relevant to the problem but [wiki-localization/locale.json](https://github.com/Requarks/wiki-localization/blob/master/locales.json) currently has:

`{"errors":[{"message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details.","locations":[{"line":3,"column":5}],"path":["localization","locales"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details.","    at Socket.<anonymous> (/app/node_modules/ioredis/built/redis/event_handler.js:95:37)","    at Object.onceWrapper (events.js:286:20)","    at Socket.emit (events.js:198:13)","    at TCP._handle.close (net.js:606:12)"]}}}],"data":{"localization":{"locales":null}}}`

As it's content.

**Comment by NGPixel** [comment]
Server issue is now fixed.
