### ISSUE TITLE
Failed to lookup view "setup" in views directory

### ISSUE THREAD

**Issue by chenkai0520** [Requarks/wiki#1205]
**Describe the bug**
when open http://localhost:3000/
```json
{
message: "Failed to lookup view "setup" in views directory "/Users/chenkai/mdata/wiki/server/views"",
error: { }
}
```

**To Reproduce**
1.open chrome http://localhost:3000/
2. See error
```
yarn run v1.19.1
$ node server
Loading configuration from /Users/chenkai/mdata/wiki/config.yml... OK
2019-11-11T04:00:53.122Z [MASTER] info: =======================================
2019-11-11T04:00:53.123Z [MASTER] info: = Wiki.js 2.0.0-beta ==================
2019-11-11T04:00:53.123Z [MASTER] info: =======================================
2019-11-11T04:00:53.123Z [MASTER] info: Initializing...
2019-11-11T04:00:53.532Z [MASTER] info: Connecting to database...
2019-11-11T04:00:53.603Z [MASTER] info: Database Connection Successful [ OK ]
2019-11-11T04:00:53.658Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-11-11T04:00:53.658Z [MASTER] info: Starting setup wizard...
2019-11-11T04:00:53.846Z [MASTER] info: Starting HTTP server on port 3000...
2019-11-11T04:00:53.846Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-11-11T04:00:53.849Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-11-11T04:00:53.849Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-11-11T04:00:53.849Z [MASTER] info: 
2019-11-11T04:00:53.849Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-11-11T04:00:53.849Z [MASTER] info: 
2019-11-11T04:00:53.849Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-11-11T04:00:57.087Z [MASTER] error: Failed to lookup view "setup" in views directory "/Users/chenkai/mdata/wiki/server/views"
TypeError: Cannot read property 'sendError' of undefined
    at /Users/chenkai/mdata/wiki/server/setup.js:371:20
    at Layer.handle_error (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:315:13)
    at /Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:315:13)
    at /Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/Users/chenkai/mdata/wiki/node_modules/express/lib/router/index.js:275:10)
    at done (/Users/chenkai/mdata/wiki/node_modules/express/lib/response.js:1007:25)
    at Function.render (/Users/chenkai/mdata/wiki/node_modules/express/lib/application.js:582:14)
    at ServerResponse.render (/Users/chenkai/mdata/wiki/node_modules/express/lib/response.js:1012:7)
    at /Users/chenkai/mdata/wiki/server/setup.js:69:9

```

**Host Info (please complete the following information):**
 - mac os
 - Wiki.js : v2.0.0-beta
 - yarn:v1.19.1
 - node:v12.12.0

**Comment by NGPixel** [comment]
Use an officially released build as detailed in the [docs](https://docs.requarks.io/install).

**Comment by chenkai0520** [comment]
> Use an officially released build as detailed in the [docs](https://docs.requarks.io/install).
thank you
