### ISSUE TITLE
Wiki does not work with git: false

### ISSUE THREAD

**Issue by Xirkolumi** [Requarks/wiki#14]
if in the configuration git connection is turned off (git: false as from docs)
during document creation there is an error pop-up with message "Something went wrong."

document is created in repo folder but is not available in wiki UI

in logs:
 Error: spawn git ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)

**Comment by Xirkolumi** [comment]
as written in comment in #9 
even if git sync is disabled it is required to be installed and available as global command.
this can be verified by typing git in cmd
