### ISSUE TITLE
Search bar doesn't work properly

### ISSUE THREAD

**Issue by wehde92** [Requarks/wiki#148]
### Actual behavior
Gives examples of page names but the results show 0.

### Expected behavior
Should return relevant search results.

### Steps to reproduce the behavior
Freshly installed on ubuntu 16.04. Nodejs version 6.11.0. npm  version 3.10.10.

I've tried accessing directly to <ip>:3000 to see if it was an issue with apache2 and it's the same issue. 

here is the error log:
`(node:1547) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
(node:1557) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
TypeError: Cannot read property 'test' of undefined
    at /home/ubuntu/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
    at Array.forEach (native)
    at /home/ubuntu/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
    at dispatchError (/home/ubuntu/wikijs/node_modules/levelup/lib/util.js:25:35)
    at /home/ubuntu/wikijs/node_modules/levelup/lib/levelup.js:228:14
    at Immediate.callNext (/home/ubuntu/wikijs/node_modules/memdown/memdown.js:166:47)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
(node:1578) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
(node:1588) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
`

**Comment by choicky** [comment]
In my installation, it doesn't work in searching Chinese words. However, it works in searching English words.

**Comment by wehde92** [comment]
![image](https://user-images.githubusercontent.com/8854624/27714908-6db1815c-5cf9-11e7-99bd-49b63cb28f53.png)


![image](https://user-images.githubusercontent.com/8854624/27714893-59b01c18-5cf9-11e7-8ef7-f26fa969f292.png)

**Comment by choicky** [comment]
it's a problem but I don't know how to resolve it.
My installation is https://note.fei-xing.com . You could try searching English words and Chinese words.

**Comment by wehde92** [comment]
Is there a job/service that runs the search indexer?

**Comment by NGPixel** [comment]
@wehde92 The search index is rebuilt on start and then updated every time a change is made to a page (or a new page created).

I'll have a look at the errors you're getting.

@choicky Please open a new ticket concerning the search not working for Chinese words.

**Comment by wehde92** [comment]
I've created a page but it refuses to show up in the directory tree:

![image](https://user-images.githubusercontent.com/8854624/27748978-25706a0e-5d97-11e7-8ffc-f1c948b15298.png)

here is the directory tree:

![image](https://user-images.githubusercontent.com/8854624/27748996-3baa6180-5d97-11e7-868a-56b91f72903b.png)

this might be relevant:

`TypeError: Cannot read property 'public/windows/7/time' of undefined
    at /home/ubuntu/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
    at Array.forEach (native)
    at /home/ubuntu/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
    at dispatchError (/home/ubuntu/wikijs/node_modules/levelup/lib/util.js:25:35)
    at /home/ubuntu/wikijs/node_modules/levelup/lib/levelup.js:228:14
    at Immediate.callNext [as _onImmediate] (/home/ubuntu/wikijs/node_modules/memdown/memdown.js:166:47)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
`
