### ISSUE TITLE
automated heroku wizard doesn't create a working wiki

### ISSUE THREAD

**Issue by cortfritz** [Requarks/wiki#150]
### Actual behavior
wizard does set up a heroku app instance and installs wiki.js.  However, this instance can only create pages, editing errors out or crashes process.  

root error seems to be
~~~~
at /app/node_modules/levelup/lib/levelup.js:223:15
2017-07-01T17:18:30.872837+00:00 app[web.1]: NotFoundError: Key not found in database [DOCUMENT-VECTOR￮entryPath￮1498927182194-1￮]
~~~~

### Expected behavior
wiki site would allow editing of pages

### Steps to reproduce the behavior
Press the "Deploy to Heroku" button on the R

1. eadme page.  
2. Fill out the forms in the Heroku wizard
3. Once the setup is complete, browse yourapp.herokuapps.com
4. Login with default admin password
5. Create a page
6. Edit the page
7. Attempt to save, get red error popup near button
8. Look at logs and see root error posted above

**Comment by cortfritz** [comment]
More of the logs:
~~~~
2017-07-01T17:58:00.960373+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=rR12QvMDxE1liHTEAAAA" host=cortwiki.herokuapp.com request_id=99324fff-0ad6-477f-b6c9-14dc41314c57 fwd="174.21.153.223" dyno=web.1 connect=0ms service=1661233ms status=101 bytes=175 protocol=https
2017-07-01T17:58:00.953135+00:00 app[web.1]: NotFoundError: Key not found in database [DOCUMENT-VECTOR￮entryPath￮1498930221240-1￮]
2017-07-01T17:58:00.953145+00:00 app[web.1]:     at /app/node_modules/levelup/lib/levelup.js:223:15
2017-07-01T17:58:00.953146+00:00 app[web.1]:     at Immediate.callNext (/app/node_modules/memdown/memdown.js:166:47)
2017-07-01T17:58:00.953147+00:00 app[web.1]:     at runCallback (timers.js:800:20)
2017-07-01T17:58:00.953148+00:00 app[web.1]:     at tryOnImmediate (timers.js:762:5)
2017-07-01T17:58:00.953148+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:733:5)
2017-07-01T17:58:00.953570+00:00 app[web.1]: /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34
2017-07-01T17:58:00.953571+00:00 app[web.1]:             tfVectors[field + sep + token] = docVector[token]
2017-07-01T17:58:00.953572+00:00 app[web.1]:                                                       ^
2017-07-01T17:58:00.953572+00:00 app[web.1]: 
2017-07-01T17:58:00.953573+00:00 app[web.1]: TypeError: Cannot read property 'home' of undefined
2017-07-01T17:58:00.953573+00:00 app[web.1]:     at /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
2017-07-01T17:58:00.953574+00:00 app[web.1]:     at Array.forEach (native)
2017-07-01T17:58:00.953575+00:00 app[web.1]:     at /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
2017-07-01T17:58:00.953575+00:00 app[web.1]:     at dispatchError (/app/node_modules/levelup/lib/util.js:25:35)
2017-07-01T17:58:00.953576+00:00 app[web.1]:     at /app/node_modules/levelup/lib/levelup.js:228:14
2017-07-01T17:58:00.953577+00:00 app[web.1]:     at Immediate.callNext [as _onImmediate] (/app/node_modules/memdown/memdown.js:166:47)
2017-07-01T17:58:00.953578+00:00 app[web.1]:     at runCallback (timers.js:800:20)
2017-07-01T17:58:00.953578+00:00 app[web.1]:     at tryOnImmediate (timers.js:762:5)
2017-07-01T17:58:00.953579+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:733:5)
2017-07-01T17:58:00.965274+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=sLtUIrtLi8l8U7rVAAAC" host=cortwiki.herokuapp.com request_id=3761d07b-a8af-4d26-872f-f766a95965c5 fwd="174.21.153.223" dyno=web.1 connect=0ms service=4908ms status=101 bytes=175 protocol=https
2017-07-01T17:58:01.038894+00:00 heroku[web.1]: State changed from up to crashed
2017-07-01T17:58:01.040206+00:00 heroku[web.1]: State changed from crashed to starting
2017-07-01T17:58:01.026662+00:00 heroku[web.1]: Process exited with status 1
2017-07-01T17:58:05.410811+00:00 heroku[web.1]: Starting process with command `node server`
2017-07-01T17:58:08.794779+00:00 app[web.1]: 2017-07-01T17:58:08.791Z - info: [SERVER] Wiki.js is initializing...
2017-07-01T17:58:09.139613+00:00 app[web.1]: 2017-07-01T17:58:09.135Z - info: [SERVER] Checking data directories...
2017-07-01T17:58:09.139626+00:00 app[web.1]: 2017-07-01T17:58:09.136Z - info: [SERVER] Data and Repository directories are OK.
cortfritz@CortBookPro ~/a/wiki> 
~~~~

**Comment by NGPixel** [comment]
See #152 for a follow-up on this issue.
