### ISSUE TITLE
(Linux SQLITE3) Update from 2.0.12 to 2.1.113 is not working

### ISSUE THREAD

**Issue by tcaduto** [Requarks/wiki#1506]
ok, so I do the update from 2.0.12 to 2.1.113 and it errors out on the SQLITE3 lib
It appears to be some version mismatch, the SQLITE binding included in the distro is newer.
If I copy the v64 from 2.012 it gets farther but then errors out on a function name that is different.

Loading configuration from /opt/wiki/config.yml... OK
2020-02-20T17:18:12.275Z [MASTER] info: =======================================
2020-02-20T17:18:12.277Z [MASTER] info: = Wiki.js 2.1.113 =====================
2020-02-20T17:18:12.277Z [MASTER] info: =======================================
2020-02-20T17:18:12.277Z [MASTER] info: Initializing...
Knex: run
$ npm install sqlite3 --save
Cannot find module '/opt/wiki/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
Error: Cannot find module '/opt/wiki/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/wiki/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Client_SQLite3._driver (/opt/wiki/node_modules/knex/lib/dialects/sqlite3/index.js:37:12)
    at Client_SQLite3.initializeDriver (/opt/wiki/node_modules/knex/lib/client.js:231:26)
    at Client_SQLite3.Client (/opt/wiki/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/opt/wiki/node_modules/knex/lib/dialects/sqlite3/index.js:19:10)

**Comment by Skymirrh** [comment]
Perhaps you can try `npm rebuild sqlite3`?

Fix found here: https://docs.requarks.io/install/linux
Originally from: https://github.com/Requarks/wiki/issues/1048#issuecomment-532696152
