### ISSUE TITLE
Clicking Save Document results in 'Error: undefined' popup

### ISSUE THREAD

**Issue by danielearwicker** [Requarks/wiki#152]
### Actual behavior
As in the title, and then clicking a second time seems to save the document okay.

### Expected behavior
Document to save on first click without error

### Steps to reproduce the behavior
Install without a git repository (that may not be necessary but it's the only non-recommended thing about my first install).

From the error log:

    TypeError: Cannot read property 'home' of undefined
        at /home/wiki/wiki/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
        at Array.forEach (native)
        at /home/wiki/wiki/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
        at dispatchError (/home/wiki/wiki/node_modules/levelup/lib/util.js:25:35)
        at /home/wiki/wiki/node_modules/levelup/lib/levelup.js:228:14
        at Immediate.callNext (/home/wiki/wiki/node_modules/memdown/memdown.js:166:47)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)

Where 'home' is the page file name being saved.

**Comment by andymac** [comment]
Also seeing this when deployed on Heroku - clicking Save causes the app to crash requiring a dyno restart on Heroku to get everything up and running again.  Same error as above .

## Expected behavior

Click save on a document, the document saves

## Actual behavior

Error message appears stating ' Error: undefined ' .  Heroku app moves into crashed state and does not respond to any requests.

## Steps to reproduce the behavior

Install with 'Deploy to Heroku' button - edit any document, then save to trigger the error.

## Logs

```
NotFoundError: Key not found in database [DOCUMENT-VECTOR￮entryPath￮1499436555186-1￮]
     at /app/node_modules/levelup/lib/levelup.js:223:15
     at Immediate.callNext (/app/node_modules/memdown/memdown.js:166:47)
     at runCallback (timers.js:800:20)
     at tryOnImmediate (timers.js:762:5)
     at processImmediate [as _immediateCallback] (timers.js:733:5)
 /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34
             tfVectors[field + sep + token] = docVector[token]
                                                       ^
 
 TypeError: Cannot read property 'home' of undefined
     at /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
     at Array.forEach (native)
     at /app/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
     at dispatchError (/app/node_modules/levelup/lib/util.js:25:35)
     at /app/node_modules/levelup/lib/levelup.js:228:14
     at Immediate.callNext [as _onImmediate] (/app/node_modules/memdown/memdown.js:166:47)
     at runCallback (timers.js:800:20)
     at tryOnImmediate (timers.js:762:5)
     at processImmediate [as _immediateCallback] (timers.js:733:5)
2017-07-07T14:10:38.883677+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=PUT path="/edit/home" host=XXX.YYY.com request_id=89530fa8-17ee-40bb-9757-4bffbddbfa6b fwd="207.35.255.2" dyno=web.1 connect=0ms service=274ms status=503 bytes=0 protocol=https
2017-07-07T14:10:38.880398+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=_M_gePh3XGNb5Aa4AAAC" host=XXX.YYY.com request_id=7bb9a515-9676-421e-88d2-1fd7d23478f9 fwd="207.35.255.2" dyno=web.1 connect=0ms service=54367ms status=101 bytes=175 protocol=https
2017-07-07T14:10:39.017975+00:00 heroku[web.1]: State changed from up to crashed
2017-07-07T14:10:39.004214+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by Bisonte-dev** [comment]
This is happening to me too. I do have a remote git repository setup and working fine.

Chrome's console shows the following

![image](https://user-images.githubusercontent.com/23046845/27987331-afe3977a-63d1-11e7-9fb1-ff52aaaa5f4e.png)

**Comment by NGPixel** [comment]
Upgrade to Beta 13 to fix this issue.
