### ISSUE TITLE
Error in postinstall on Windows 10 (Buffer.alloc is not a function)

### ISSUE THREAD

**Issue by andydevs** [Requarks/wiki#153]
### Actual Behavior

When the install runs it produces this error

```
... /pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (C:\ ... \node_modules\tar\lib\pack.js:32:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ ... \node_modules\tar\lib\create.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ ... \node_modules\tar\index.js:4:30)
    at Module._compile (module.js:409:26)
```

### Expected Behavior

Should successfully run `install.js` and make `node ./wiki.js` available

### Steps to reproduce behavior

I'm running npm v4.2.0 and node v4.4.1 on Windows 10. I'm using regular old command line.

[I've attached the debug log here](https://github.com/Requarks/wiki/files/1126749/2017-07-06T04_27_58_300Z-debug.zip)

**Comment by NGPixel** [comment]
Your version of Node is too old. Upgrade to 6.9.0 or later, as stated in the prerequisites.

**Comment by andydevs** [comment]
Tried that, it works. Thanks!
