### ISSUE TITLE
TypeError: Cannot read property 'home' of undefined

### ISSUE THREAD

**Issue by hartbit** [Requarks/wiki#156]
### Actual behavior

Very often getting a "Error: undefined" when saving pages.

### Expected behavior

It should not error.

### Steps to reproduce the behavior

The logs show this error when saving:

```
TypeError: Cannot read property 'home' of undefined
    at /Users/david/Projects/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:34:55
    at Array.forEach (native)
    at /Users/david/Projects/wikijs/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:33:41
    at dispatchError (/Users/david/Projects/wikijs/node_modules/levelup/lib/util.js:25:35)
    at /Users/david/Projects/wikijs/node_modules/levelup/lib/levelup.js:228:14
    at Immediate.callNext (/Users/david/Projects/wikijs/node_modules/memdown/memdown.js:166:47)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by hartbit** [comment]
Oops, duplicate of #152
