### ISSUE TITLE
S3 Export all don't work

### ISSUE THREAD

**Issue by rlarrode** [Requarks/wiki#1604]
**Describe the bug**
In s3 Storage Admin section, when i click on export all, i get success popup but nothing happen on s3 side.
On server side i get following error
`[MASTER] warn: Invalid Handler for Storage Target`

When i manually update a page, it is successfully saved in my S3

**To Reproduce**
1. Provide S3 Storage in Administration Panel
2. Click on "Export All"
3. Check your S3 bucket (nothing change)
4. See error in server logs

**Expected behavior**
All DB content should be transfered to S3 bucket

**Host Info:**
 - OS: Debian 9.0 on AWS EC2
 - Wiki.js version: 2.1.113
 - Database engine: postgres 9.5

Thanks

**Comment by Blizarre** [comment]
I don't know if this might help, but I get the same problem.
On top of that, when I go the admin storage page, I get a popup `An unexpected error occured.`. The response to the call to the GraphQL endpoint made by the browser contains this error:
```
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "Error: Cannot return null for non-nullable field StorageStatus.message.",
              "    at completeValue (/wiki/node_modules/graphql/execution/execute.js:560:13)",
              "    at completeValueCatchingError (/wiki/node_modules/graphql/execution/execute.js:495:19)",
              "    at resolveField (/wiki/node_modules/graphql/execution/execute.js:435:10)",
              "    at executeFields (/wiki/node_modules/graphql/execution/execute.js:275:18)",
              "    at collectAndExecuteSubfields (/wiki/node_modules/graphql/execution/execute.js:713:10)",
              "    at completeObjectValue (/wiki/node_modules/graphql/execution/execute.js:703:10)",
              "    at completeValue (/wiki/node_modules/graphql/execution/execute.js:591:12)",
              "    at completeValueCatchingError (/wiki/node_modules/graphql/execution/execute.js:495:19)",
              "    at /wiki/node_modules/graphql/execution/execute.js:618:25",
              "    at Array.forEach (<anonymous>)",
              "    at forEach (/wiki/node_modules/iterall/index.js:83:25)",
              "    at completeListValue (/wiki/node_modules/graphql/execution/execute.js:614:24)",
              "    at completeValue (/wiki/node_modules/graphql/execution/execute.js:573:12)",
              "    at /wiki/node_modules/graphql/execution/execute.js:492:16",
              "    at runMicrotasks (<anonymous>)",
              "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
              "    at async Promise.all (index 0)",
              "    at async Promise.all (index 0)"
            ]
          }
        }
      }
```

**Comment by regevbr** [comment]
I have the same issue...
