### ISSUE TITLE
Installation error when running "node server" command

### ISSUE THREAD

**Issue by dand561** [Requarks/wiki#1689]
### Actual behavior
(node:8849) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.init (/home/user/wiki/server/core/db.js:30:33)
    at Object.init (/home/user/wiki/server/core/kernel.js:13:35)
    at Object.<anonymous> (/home/user/wiki/server/index.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:8849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8849) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
### Expected behavior
Wiki should start running
### Steps to reproduce the behavior
Followed all the steps in the installation page. I must mention I have MongoDB running and I want to use it as I want to migrate from v1.0.76, but there is no configuration page for Mongo on your site. Is it possible to use MongoDB further or this is actually the problem and I should switch to smth else?

**Comment by NGPixel** [comment]
Please **[read the docs](https://docs.requarks.io/install/requirements#database)** as MongoDB is not supported for v2.
