### ISSUE TITLE
Installation on Ubuntu with or without Plesk and Docker, please help me

### ISSUE THREAD

**Issue by SnowAndFireFox** [Requarks/wiki#1712]
hi i have already started several attempts to migrate wiki.js to my ubuntu server. 

I am currently using Plesk Obsidian with Docker, but I have already tested it directly on the server. Unfortunately without success. I have tried several installation instructions from wiki.js.

**Host Info :**
Ubuntu 18.04, Docker with Plesk / Docker without Plesk
Wiki.js version: [e.g. 2.2.51]
Database engine: mariadb / mysql

I always get the following error message: 

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Object.init (/wiki/server/core/db.js:32:37)
    at Object.init (/wiki/server/core/kernel.js:13:35)
    at Object.<anonymous> (/wiki/server/index.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NGPixel** [comment]
Looks like your DB config in config.yml is missing or invalid.
