### ISSUE TITLE
Failed upgrade 2.2.50 to 2.3.51

### ISSUE THREAD

**Issue by King-GO** [Requarks/wiki#1745]
OS: [WIN7 XAMPP]
Wiki.js version: [2.2.50]
Database engine: [ 10.4.10, 10.4.10-MariaDB]

download wiki-js-windows.tar.gz and follow update procedure, 

Loading configuration from d:\wiki.js\config.yml... OK
2020-04-21T04:29:59.075Z [MASTER] info: =======================================
2020-04-21T04:29:59.078Z [MASTER] info: = Wiki.js 2.3.51 ======================
2020-04-21T04:29:59.079Z [MASTER] info: =======================================
2020-04-21T04:29:59.080Z [MASTER] info: Initializing...
(node:12984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '
toString' of null
    at Object.init (d:\wiki.js\server\core\db.js:35:37)
    at Object.init (d:\wiki.js\server\core\kernel.js:13:35)
    at Object.<anonymous> (d:\wiki.js\server\index.js:33:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:12984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:12984) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

**Comment by NGPixel** [comment]
Make sure your db password (`db.pass`) is properly defined in your config.yml.

**Comment by King-GO** [comment]
Thank you for your hint. 

db.pass should not leave blank, use **''** instead and working

**Comment by Smankusors** [comment]
> Thank you for your hint.
> 
> db.pass should not leave blank, use **''** instead and working

so on the previous version you write `db.pass=` and on the 2.3.51 you write `db.pass=''` for the blank passsword?

**Comment by King-GO** [comment]
> > Thank you for your hint.
> > db.pass should not leave blank, use **''** instead and working
> 
> so on the previous version you write `db.pass=` and on the 2.3.51 you write `db.pass=''` for the blank passsword?

Yes
