### ISSUE TITLE
Unable to start wiki-js 2.3.77 on Mac OS

### ISSUE THREAD

**Issue by fhiegel** [Requarks/wiki#1787]
**Describe the bug**
After upgrading from 2.2.51, i get the following error from 2.3.77 : 

```
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for '~/wiki-js-v2.3.77/node_modules/nanoid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (~/wiki-js-v2.3.77/server/index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
````

**To Reproduce**
1. Dowload wiki-js 2.3.77
2. Go into wiki-js folder
3. run server with 'node server'

**Expected behavior**
Server whould start properly

**Host Info (please complete the following information):**
 - OS: MacOS Darwin (darwin) 16.7.0 x64
 - Wiki.js version: 2.3.77
 - Database engine: 12.2
 - NodeJS : 13.2.0

**Additional context**
Thank for your great job here.

**Comment by asnyder** [comment]
Same issue here on AWS Linux 2. Created a screencast for this, but fhiegel summed it up perfectly!!

**Comment by FelixSFD** [comment]
Same here, but on Ubuntu 18.04:
```
internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for '/var/wikijs2/node_modules/nanoid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/wikijs2/server/index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by AlexandreDC** [comment]
same as https://github.com/Requarks/wiki/issues/1797

**Comment by fhiegel** [comment]
Works perfectly after updating node from `v13.2.0` to `v14.1.0`.
Thanks @sray for comment in #1797.

**Comment by asnyder** [comment]
This is now working for me after updating NodeJS to node v14.2.0 (npm v6.14.4).

**Comment by NGPixel** [comment]
Added a note in the [docs](https://docs.requarks.io/en/install/requirements#nodejs) about Node.js 13.0 to 13.2 not being supported because of the ESM bug.

On another note, the 13.x release has reached its end-of-life and is no longer supported anyway.
