### ISSUE TITLE
Something is missing

### ISSUE THREAD

**Issue by NigelLuckie** [Requarks/wiki#1969]
I've got everything installed that I'm aware of.  GIT, Mongo, etc.

The configuration finishes successfully without errors.

When I run node server I get the following.

PS E:\wiki> node server
2020-05-31T18:03:59.455Z - info: [SERVER] Wiki.js is initializing...
2020-05-31T18:03:59.629Z - info: [SERVER] Checking data directories...
2020-05-31T18:03:59.633Z - info: [SERVER] Data and Repository directories are OK.
2020-05-31T18:04:00.159Z - info: [SERVER] Checking Git repository...
E:\wiki\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:240
    this._origin = whatwgURL.serializeURLToUnicodeOrigin(parsed);
                             ^

TypeError: whatwgURL.serializeURLToUnicodeOrigin is not a function
    at new DocumentImpl (E:\wiki\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:240:30)
    at Object.setup (E:\wiki\node_modules\jsdom\lib\jsdom\living\generated\Document.js:741:17)
    at Object.create (E:\wiki\node_modules\jsdom\lib\jsdom\living\generated\Document.js:711:10)
    at new Window (E:\wiki\node_modules\jsdom\lib\jsdom\browser\Window.js:68:29)
    at exports.jsdom (E:\wiki\node_modules\jsdom\lib\jsdom.js:109:18)
    at Object.exports.patch (E:\wiki\node_modules\mathjax-node\lib\patch\jsdom.js:286:18)
    at Object.<anonymous> (E:\wiki\node_modules\mathjax-node\lib\main.js:35:29)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\wiki\server\libs\markdown.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\wiki\server\index.js:43:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
PS E:\wiki>

**Comment by Smankusors** [comment]
where's your host info?
