### ISSUE TITLE
Azure AD login fails with "Invalid email / username or password."

### ISSUE THREAD

**Issue by Jamesits** [Requarks/wiki#1992]
**Describe the bug**

**To Reproduce**
1. Set up Azure AD auth according to [doc](https://docs.requarks.io/en/auth/azure)
2. Enable self-registration
3. Try to log in with Azure AD

**Expected behavior**
I should be able to log in

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.3.81
 - Database engine: MariaDB 10.4.12-MariaDB-1:10.4.12+maria~buster-log

**Additional context**

JWT claim looks good to me. The `email` and `preferred_username` both exist but are different. 

Web page log:
```
Oops, something went wrong...
Invalid email / username or password.
AuthLoginFailed 1002: Invalid email / username or password.
    at /wiki/server/models/users.js:282:38
    at allFailed (/wiki/node_modules/passport/lib/middleware/authenticate.js:107:18)
    at attempt (/wiki/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at Strategy.strategy.fail (/wiki/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at Strategy.failWithLog (/wiki/node_modules/passport-azure-ad/lib/oidcstrategy.js:1498:15)
    at /wiki/node_modules/passport-azure-ad/lib/oidcstrategy.js:662:21
    at /wiki/node_modules/passport-azure-ad/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/wiki/node_modules/passport-azure-ad/node_modules/async/lib/async.js:1206:34)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

Console log:
```
2020-06-04T09:50:38.011Z [MASTER] info: Authentication Strategy azure: [ OK ]
2020-06-04T09:50:38.012Z [MASTER] info: Authentication Strategy github: [ OK ]
2020-06-04T09:50:38.012Z [MASTER] info: Authentication Strategy local: [ OK ]
```

**Comment by Smankusors** [comment]
What do you mean by :
> The `email` and `preferred_username` both exist but are different.

?

**Comment by Jamesits** [comment]
@Smankusors There are both `email` and `preferred_username` claims but their values are different.

**Comment by smg-bg** [comment]
Same here...

Somehow it was working the first few times, but then it stopped working after I disabled the self-registration option.However if I return it back it still crashes with the above message.
