### ISSUE TITLE
First run got "UnhandledPromiseRejectionWarning" error

### ISSUE THREAD

**Issue by coamtaker618** [Requarks/wiki#2265]
Error thrown on 1st run of new install on new system (Ubuntu 18.04 headless).

Ran "node server" & got a "UnhandledPromiseRejectionWarning"

note:
I am pointing to a new postgres database with user & tables & permissions setup for wikijs.

```
node server
Loading configuration from /home/server/wiki-v001/config.yml... OK
2020-08-04T21:58:07.037Z [MASTER] info: =======================================
2020-08-04T21:58:07.041Z [MASTER] info: = Wiki.js 2.4.107 =====================
2020-08-04T21:58:07.042Z [MASTER] info: =======================================
2020-08-04T21:58:07.042Z [MASTER] info: Initializing...
(node:28061) UnhandledPromiseRejectionWarning: /home/server/wiki-v001/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/server/wiki-v001/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
(node:28061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by NGPixel** [comment]
Are you running Node.js **10.12 or later**?

**Comment by coamtaker618** [comment]
Apparently not!  Looks like ubuntu 18.04 LTS comes with v8.10.0   :(

`according to node --version`

Is there a recommended source to add to the repo?

**Comment by Smankusors** [comment]
> Apparently not! Looks like ubuntu 18.04 LTS comes with v8.10.0 :(
> 
> `according to node --version`
> 
> Is there a recommended source to add to the repo?

you can follow the linked guide from [official docs](https://nodejs.org/en/download/package-manager/).

**Comment by coamtaker618** [comment]
Confirming that updating node fixed this.

Guess this is what I get for not double-checking the versions of pre-reqs!
