### ISSUE TITLE
Postgres config references for new wikijs install

### ISSUE THREAD

**Issue by coatmaker618** [Requarks/wiki#2287]
**Question**
I am trying to setup a new install of wikijs with postgres.  However I am not having luck setting up postgres.  Are there any walkthroughs or other references for setting up a new postgres database for wikijs?

I saw a list of migration tools on the wiki, but I am talking of a fresh install. Something like the "systemctl" on the initial install page would be perfect!

** More Background**
I have an old version of wikijs (still v2.something) that ran on mariadb, but never used it for more than testing.  I also had some weird configs in there as a result of some bad/stupid tests I ran, so I'd prefer to start fresh over migrate.

To be clear, postgres is installed fine (on a separate machine) and I am able to connect with the postgres client. I am also able to run the new instance from the mariadb database but when I put in the postgres configs, it seems to connect ok & then immediately fail after the message to go to port 3000 appears.

As I was able to do this in mariadb but find myself unsuccessful in postgres; I think all I need is some reference showing me a "simple" config for postgres.  Since wikijs seems to be strongly migrating towards postgres over mariadb or mysql, it seems likely to me that others will need such a reference in the future.

Host Info:
OS: Ubuntu 18.04
Wiki.js version: 2.4.107
Database engine: postgres (hopefully)

Actual error

```
Loading configuration from /home/server/wiki-v001/config.yml... OK
2020-08-12T00:41:37.343Z [MASTER] info: =======================================
2020-08-12T00:41:37.347Z [MASTER] info: = Wiki.js 2.4.107 =====================
2020-08-12T00:41:37.348Z [MASTER] info: =======================================
2020-08-12T00:41:37.349Z [MASTER] info: Initializing...
2020-08-12T00:41:37.991Z [MASTER] info: Using database driver pg for postgres [ OK ]
2020-08-12T00:41:38.020Z [MASTER] info: Connecting to database...
2020-08-12T00:41:38.062Z [MASTER] info: Database Connection Successful [ OK ]
2020-08-12T00:41:38.138Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2020-08-12T00:41:38.138Z [MASTER] info: Starting setup wizard...
2020-08-12T00:41:38.336Z [MASTER] info: Starting HTTP server on port 3000...
2020-08-12T00:41:38.337Z [MASTER] info: HTTP Server on port: [ 3000 ]
2020-08-12T00:41:38.343Z [MASTER] info: HTTP Server: [ RUNNING ]
2020-08-12T00:41:38.343Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2020-08-12T00:41:38.343Z [MASTER] info:
2020-08-12T00:41:38.344Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2020-08-12T00:41:38.344Z [MASTER] info:
2020-08-12T00:41:38.345Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2020-08-12T00:44:08.805Z [MASTER] error: Not Found
TypeError: Cannot read property 'sendError' of undefined
    at /home/server/wiki-v001/server/setup.js:384:20
    at Layer.handle_error (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:315:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki-v001/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki-v001/node_modules/express/lib/router/index.js:275:10)
    at /home/server/wiki-v001/server/setup.js:374:5
    at Layer.handle [as handle_request] (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:317:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki-v001/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki-v001/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/server/wiki-v001/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:317:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
2020-08-12T00:44:09.813Z [MASTER] error: Not Found
```

please note that `/home/server/wiki` is a softlink to `/home/server/wiki-v001`

Also not that this error repeats verbatum roughly once a second indefinitely.

**Comment by jianbin-wei** [comment]
can you please post the error messages?

**Comment by coamtaker618** [comment]
Oops, good catch @jianbin-wei original post updated!

**Comment by Smankusors** [comment]
Hmm... what node.js version you installed?

**Comment by coamtaker618** [comment]
server@wikijs:~/wiki$ node --version
v14.7.0

**Comment by coamtaker618** [comment]
As far as I can tell that's a valid version of nodejs?

**Comment by jianbin-wei** [comment]
This is what I use and it works.  Maybe you want to try a clean setup?
```
db:
  type: postgres

  host: localhost
  port: 5432
  user: wikijs
  pass: wikijs
  db: wiki
  ssl: false
```

node version
```
 $ node -v
v13.8.0
```

**Comment by coamtaker618** [comment]
@jianbin-wei That is very close to what I'm using, except I have Postgres running on a different machine so I'm using the IP of that machine instead of localhost.

How did you setup postgres? What about the wikijs user & table?

**Comment by jianbin-wei** [comment]
This is how I run `postgres -D /usr/local/var/postgres`

Also you may want to try the docker+vs code https://docs.requarks.io/dev if everything else does not work.

**Comment by coamtaker618** [comment]
I'll have to compare commands, but that's probably how mine is running (I'm using systemctl to run postgres, but it's probably just doing the same thing behind the scenes).

Also, I'm running these in headless Linux VMs.  I have not figured out a way to get VSCode to run in such an environment.  If I was able to figure this issue out, I would be greatly appreciative :)

I'm just shooting in the dark. But I feel like it MUST be a postgres issue if switching to a different database (Mariadb) on the same wiki.js install works, right?

**Comment by coamtaker618** [comment]
What about the commands used in Postgres to create the permissions for the user & table?  Maybe that's the problem?  How did you create the user/table & how did you give that user permission to modify the table as needed?

**Comment by jianbin-wei** [comment]
I set it as the owner for my wiki database.

**Comment by coamtaker618** [comment]
> I set it as the owner for my wiki database.

*nod* That's what I intended to do, but I'm wondering if it took or if I did it right?  Would you mind sharing the commands that you used?

**Comment by jianbin-wei** [comment]
I used pgadmin for that 😀

**Comment by coamtaker618** [comment]
Ohh, this seems way nicer than CLI & it has a web server!!  I like it :)

Thanks @jianbin-wei

**Comment by coamtaker618** [comment]
Update:

The system hosting my postgres died & I was unable to recover an uncorrupted version of postgres.  Therefore, I have created a new postgres from scratch & am attempting to set it up from scratch.

Commands in postgres (after install)
```
 create user wikijs_user password '*redacted*';
create database wikijs_db;
GRANT ALL PRIVILEGES ON DATABASE wikijs_db TO wikijs_user;
```

Also modified `/etc/postgresql/12/main/pg_hba.conf` to allow external connections & restarted service.



I am still getting the following error whne I run 'node server' on the wikijs machine.


```
2020-08-26T21:55:53.734Z [MASTER] info: =======================================
2020-08-26T21:55:53.738Z [MASTER] info: = Wiki.js 2.4.107 =====================
2020-08-26T21:55:53.739Z [MASTER] info: =======================================
2020-08-26T21:55:53.739Z [MASTER] info: Initializing...
2020-08-26T21:55:54.420Z [MASTER] info: Using database driver pg for postgres [ OK ]
2020-08-26T21:55:54.447Z [MASTER] info: Connecting to database...
2020-08-26T21:55:54.636Z [MASTER] info: Database Connection Successful [ OK ]
2020-08-26T21:55:55.865Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2020-08-26T21:55:55.866Z [MASTER] info: Starting setup wizard...
2020-08-26T21:55:56.181Z [MASTER] info: Starting HTTP server on port 80...
2020-08-26T21:55:56.182Z [MASTER] info: HTTP Server on port: [ 80 ]
2020-08-26T21:55:56.190Z [MASTER] info: HTTP Server: [ RUNNING ]
2020-08-26T21:55:56.191Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2020-08-26T21:55:56.192Z [MASTER] info:
2020-08-26T21:55:56.193Z [MASTER] info: Browse to http://localhost:80/ to complete setup!
2020-08-26T21:55:56.194Z [MASTER] info:
2020-08-26T21:55:56.195Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2020-08-26T21:55:56.814Z [MASTER] error: Not Found
TypeError: Cannot read property 'sendError' of undefined
    at /home/server/wiki-v001/server/setup.js:384:20
    at Layer.handle_error (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:315:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki-v001/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki-v001/node_modules/express/lib/router/index.js:275:10)
    at /home/server/wiki-v001/server/setup.js:374:5
    at Layer.handle [as handle_request] (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:317:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/server/wiki-v001/node_modules/express/lib/router/index.js:335:12)
    at next (/home/server/wiki-v001/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/server/wiki-v001/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/server/wiki-v001/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/server/wiki-v001/node_modules/express/lib/router/index.js:317:13)
    at /home/server/wiki-v001/node_modules/express/lib/router/index.js:284:7
```

**Comment by coamtaker618** [comment]
So looking at the setup.js code, the last of my output seems to correspond to the last few lines of code (as far as I can tell, I'm far from an expert).  So it may not be setup but whatever is run next---what would that be & how would I tell?  trying to see if @Smankusors is correct in the assumption that this is NOT postgres related, which means it must be node/js related, right?

**Comment by Smankusors** [comment]
hmm it could be... well it seems like the error happens when `WIKI.telemetry` is null, if you read the stack trace. I don't know why this is null... Maybe I should mention @NGPixel for this 😕 

https://github.com/Requarks/wiki/blob/9e08718ee904046f8b2294ef6ac79e8a75a451e3/server/setup.js#L384

**Comment by coamtaker618** [comment]
The install page https://docs.requarks.io/install/requirements

does not list acceptable Linux versions. I'm using Ubuntu Server 20.04 could that be an issue in some way, given that we know my version of NodeJS is good?

**Comment by Smankusors** [comment]
> The install page https://docs.requarks.io/install/requirements
> 
> does not list acceptable Linux versions. I'm using Ubuntu Server 20.04 could that be an issue in some way, given that we know my version of NodeJS is good?

hmm IMO it's recommended to install nodejs from the instructions provided by [official website here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages). With this you can choose which version do you want. 

---

Or, maybe skip the package manager and just download the binary only.

**Comment by coamtaker618** [comment]
Whelp, I'm running v14.7.0 of NodeJS.  Can't remember if it came with or if I installed manually.  Either way, that's the version on the OS (which I believe is fine).

I was wondering if there was anything else that was being called that could be problematic.  Like some bash function or OS call?

**Comment by Smankusors** [comment]
Hmm idk really. Currently I just use Docker to avoid potential issues like you describe. 😉

**Comment by coamtaker618** [comment]
Hahaha, I always run into weird issues with Docker so I've learned to avoid it myself >_>

**Comment by Smankusors** [comment]
> Hahaha, I always run into weird issues with Docker so I've learned to avoid it myself >_>

Huh weird issues?

**Comment by coamtaker618** [comment]
Haven't tried with this specifically.  But I'm still stuck on the fact that changing databases seems to work

**Comment by LiYouliang** [comment]
I meet the same issue when using the example of a Docker Compose from https://docs.requarks.io/install/docker

`
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
`

But have no idea how to solve it.

**Comment by coamtaker618** [comment]
Also wanted to bump.  I just made a clean VM yesterday & followed the instructions on https://docs.requarks.io/install/ubuntu  (which include docker, so I used docker).  I still get the same result >_<
