### ISSUE TITLE
node server TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by saranvdev** [Requarks/wiki#2302]
**Question**
I'm trying to run the wiki, but something seems to not work:
```
node --trace-warnings server
Loading configuration from /home/saran/Pobrane/wiki/config.yml... OK
2020-08-18T10:11:26.150Z [MASTER] info: =======================================
2020-08-18T10:11:26.151Z [MASTER] info: = Wiki.js 2.4.107 =====================
2020-08-18T10:11:26.151Z [MASTER] info: =======================================
2020-08-18T10:11:26.151Z [MASTER] info: Initializing...
(node:31050) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Object.init (/home/saran/Pobrane/wiki/server/core/db.js:35:37)
    at Object.init (/home/saran/Pobrane/wiki/server/core/kernel.js:13:35)
    at Object.<anonymous> (/home/saran/Pobrane/wiki/server/index.js:33:13)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:31050) TypeError: Cannot read property 'toString' of null
    at Object.init (/home/saran/Pobrane/wiki/server/core/db.js:35:37)
    at Object.init (/home/saran/Pobrane/wiki/server/core/kernel.js:13:35)
    at Object.<anonymous> (/home/saran/Pobrane/wiki/server/index.js:33:13)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
(node:31050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

```
**Host Info:**
OS: Manjaro
Wiki.js version: 2.4.107
Database engine: postgres 12.3

**Comment by Smankusors** [comment]
what is your Node.js version btw?

**Comment by saranvdev** [comment]
v14.7.0 @Smankusors

**Comment by Smankusors** [comment]
Hmm what is your `config.yml` btw?

**Comment by saranvdev** [comment]
Hey, looks like I had to manually create the database and database user. 
Fixed now, thanks.

**Comment by Smankusors** [comment]
Ok, if your issue is solved, feel free to close this issue 😉
