### ISSUE TITLE
Unexpected exception while running wiki.js

### ISSUE THREAD

**Issue by siddhartha-lal** [Requarks/wiki#2391]
I am unable to start the wiki service. I have recently upgraded to the latest version and I am getting the following message:
(node:10428) UnhandledPromiseRejectionWarning: /var/www/wiki.miit.edu.mm/wikijs/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/wiki.miit.edu.mm/wikijs/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
(node:10428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Actual behavior
Wiki.js service does not start.

### Expected behavior
Wiki.js service should start.

### Steps to reproduce the behavior
Not sure about this. I installed the latest version to make sure it was not a bug, but the error seems to have persisted.

![Untitled](https://user-images.githubusercontent.com/56102539/92430545-24650500-f1bb-11ea-80df-3802b9941802.png)

**Comment by Smankusors** [comment]
please, where is the host info?

**Comment by siddhartha-lal** [comment]
Sorry.

I am running it on a Linux VM with Ubuntu 18.04 as the OS. Node version is 8.10.0.

**Comment by Smankusors** [comment]
please [read the requirements](https://docs.requarks.io/install/requirements#nodejs).

You need at least 10.12 or later
