### ISSUE TITLE
Design wonders for a secondary-postgres-db as a raw data provider. (How to debug and step through server-side code? this one SOLVED)

### ISSUE THREAD

**Issue by Maxzor** [Requarks/wiki#2465]
Looking to get started with contributing, I am a js beginner.

I would like my wiki to hit another postgresql db, in the same cluster as the wikijs one : my goal is to display data tables from this secondary db within the wiki pages.
I started fiddling encapsulating Adminer renders in iframes but would like to do it the right way.

AFAIK :
- the GraphQL endpoint hits Knex to ObjectRelationalMap and produce SQL ?
- I would need a new ERM (extension rendering module) like jquery datatable, interfaced with new graphql schemas and resolvers ?

```yarn dev``` from vscode console and 2.5.144 code works perfectly fine.
~~How do you run a debug session and step through nodejs code?~~ P.S. : Solved see below
As a start I would like to get a grasp at server/core/db.js and explore the interaction between graphql and knex.

Best regards, Maxime

**Comment by Maxzor** [comment]
## Attach (inspector protocol)
![image](https://user-images.githubusercontent.com/16599683/93390073-694d0380-f86d-11ea-8908-7de461f482ef.png)

## Launch program
```text
/usr/local/bin/node ./../wiki\server.js
Debugger listening on ws://127.0.0.1:43349/c40a0e83-30a4-4db0-8f22-9b6a09b04a57
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:43349/c40a0e83-30a4-4db0-8f22-9b6a09b04a57
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/wiki\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Attach to Port
![image](https://user-images.githubusercontent.com/16599683/93390257-b4671680-f86d-11ea-87b9-6fdee8cfb0bb.png)

**Comment by Maxzor** [comment]
Oh ok -.- that's the fourth, Node.js (preview) obv...
![image](https://user-images.githubusercontent.com/16599683/93390339-d6609900-f86d-11ea-9049-3362cac454c8.png)

:+1:

**Comment by Maxzor** [comment]
Leaving open a few days in case of design hints, BR

**Comment by Maxzor** [comment]
So from what I understood, I will need
- an ERM, custom jquery-datable or the likes UI rendering module
- an raw extension module, which will hold a second knex instance to query the secondary db. Will not bother with graphql on this subject for now.

**Comment by Maxzor** [comment]
How could I design a tag system to place in markdown, that would trigger a custom module rendering of the datatable component?
