### ISSUE TITLE
`docker-compose` ran failed

### ISSUE THREAD

**Issue by shockw4ver** [Requarks/wiki#2468]
**Question**
Cannot run docker-compose successfully in `remote development` mode of vscode.

**Host Info (please complete the following information):**
OS: macOS 10.15.6
Wiki.js version: master
Database engine: postgres 9.7

**Description**
I tried to develope wiki by following official guide but fail at run `docker-compose`, and got error-logs below:
```
[31 ms] Start: Resolving remote
[33 ms] Setting up container for folder or workspace: /Users/zhangyongchao/selfspace/wiki.js/wiki

[34 ms] Start: Check Docker is running
[34 ms] Start: Run: docker info
[147 ms] Start: Run: docker-compose version --short
[596 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=containers --filter label=com.docker.compose.service=wiki
[640 ms] Start: Run: docker-compose -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml config --services
[1097 ms] db
adminer
wiki
[1097 ms] 
[1098 ms] Start: Run: docker events --format {{json .}} --filter status=start
[1103 ms] Start: Run: docker-compose --project-name containers -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml up -d --build
Building wiki
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 67, in main
    command()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 126, in perform_command
    handler(command, command_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 1070, in up
    to_attach = up(False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 1066, in up
    cli=native_builder,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/project.py", line 615, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/service.py", line 346, in ensure_image_exists
    self.build(cli=cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/service.py", line 1125, in build
    platform=self.platform,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/api/build.py", line 261, in build
    self._set_auth_headers(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/api/build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 311, in get_all_credentials
    reg, store_name
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 287, in _get_store_instance
    name, environment=self._credstore_env
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/credentials/store.py", line 25, in __init__
    self.program
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[2419 ms] Command failed: docker-compose --project-name containers -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml up -d --build
```
Is docker-credential-gcloud required to build wiki?

**Comment by NGPixel** [comment]
```
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
```
This seems to be an issue with your environment, not Wiki.js or its docker-compose file.
