### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by alexrygalov** [Requarks/wiki#251]
### Actual behavior

When I try to install wikijs according this manual https://docs.requarks.io/wiki/install I get some errors. It seems to me that the host cannot download modules and dependencies. Tried to install on external host ( Digital Ocean ) the result was the same. Probably I do something in a wrong way, but cannot find what exactly.

Ubuntu 16.04.03 LTS Linux vagrant 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
   < INSTALL >

[1/3] Fetching latest build...
curl: (6) Could not resolve host: of
curl: (6) Could not resolve host: the
curl: (6) Could not resolve host: pools
curl: (6) Could not resolve host: have
curl: (6) Could not resolve host: an
curl: (6) Could not resolve host: opened
curl: (6) Could not resolve host: connection
curl: (6) Could not resolve host: and
curl: (6) Could not resolve host: failed
curl: (6) Could not resolve host: to
curl: (6) Could not resolve host: open
curl: (6) Could not resolve host: a
curl: (6) Could not resolve host: new
curl: (6) Could not resolve host: one

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[2/3] Fetching dependencies...
curl: (6) Could not resolve host: of
curl: (6) Could not resolve host: the
curl: (6) Could not resolve host: pools
curl: (6) Could not resolve host: have
curl: (6) Could not resolve host: an
curl: (6) Could not resolve host: opened
curl: (6) Could not resolve host: connection
curl: (6) Could not resolve host: and
curl: (6) Could not resolve host: failed
curl: (6) Could not resolve host: to
curl: (6) Could not resolve host: open
curl: (6) Could not resolve host: a
curl: (6) Could not resolve host: new
curl: (6) Could not resolve host: one

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[3/3] Creating config file...
cp: cannot stat 'config.sample.yml': No such file or directory
-> Installation Complete
```

And that happens after i run `node wiki configure`

```
module.js:473
      throw err;
      ^

Error: Cannot find module '/root/node_modules/wiki.js/install.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

**Comment by heschlie** [comment]
Seeing this as well it looks like the API endpoint that holds the version number is having trouble:

```shell
$ curl -L https://beta.requarks.io/api/version/stable
None of the pools have an opened connection and failed to open a new one.
```

**Comment by NGPixel** [comment]
Fixed!
