### ISSUE TITLE
Wiki won't install

### ISSUE THREAD

**Issue by theAlchemist-dev** [Requarks/wiki#253]
### Actual behavior
The wiki source won't install on my system, a FreeBSD 10.3 build.

Apparently the FreeBSD file system does not support un-tarring from the /dev/sa0 location:

```
$ curl -sSo- https://wiki.js.org/install.sh | bash


 __    __ _ _    _    _
/ / /\ \ (_) | _(_)  (_)___
\ \/  \/ / | |/ / |  | / __|
 \  /\  /| |   <| |_ | \__ \
  \/  \/ |_|_|\_\_(_)/ |___/
                   |__/
   < INSTALL >

[1/3] Fetching latest build...
tar: Error opening archive: Failed to open '/dev/sa0'
curl: (23) Failed writing body (0 != 16360)
[2/3] Fetching dependencies...
tar: Error opening archive: Failed to open '/dev/sa0'
curl: (23) Failed writing body (0 != 16360)
[3/3] Creating config file...
cp: config.sample.yml: No such file or directory
-> Installation Complete

- Launch configuration wizard: node wiki configure
- Start Wiki.js server: node wiki start

$ node wiki start
module.js:491
    throw err;
    ^

Error: Cannot find module '/data/node_root/wiki/wiki'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

I tried installing it with NPM, but the result is the same...

### Expected behavior
That the installer works...

I also tested in on a CentOS device and that works fine.

### Steps to reproduce the behavior
Just try to install it.

**Comment by NGPixel** [comment]
The installer script simply runs:
`curl -L -s -S https://github.com/Requarks/wiki/releases/download/v$VERSION/wiki-js.tar.gz | tar xz -C .`

If you are aware of an alternative command that would work on FreeBSD, let me know and I'll add it to the script.

**Comment by theAlchemist-dev** [comment]
Woah, that's a fast response!
Thank you!

----

After searching a bit, I found adding `-f -` to the `tar` command to fix it:

```
echo "[1/3] Fetching latest build..."
curl -L -s -S https://github.com/Requarks/wiki/releases/download/v$VERSION/wiki-js.tar.gz | tar xz -C .

echo "[2/3] Fetching dependencies..."
curl -L -s -S https://github.com/Requarks/wiki/releases/download/v$VERSION/node_modules.tar.gz | tar xz -C .
```
