### ISSUE TITLE
Wiki not running - no logs

### ISSUE THREAD

**Issue by theAlchemist-dev** [Requarks/wiki#254]
I am trying to get wiki.js running on my FreeBSD 10.3 server.
I got the wiki.js installed in my node root folder, /data/node_root, where I have all my node projects running.

I configured the wiki to run on localhost, port 4080. 
All the configuration passed the tests.

I added a vhost proxy record to access the wiki via Apache. 
This is the same for all my node projects and usually works fine.

### Actual behavior
I keep getting 503 requests, Apache states that the address refused connection.

I tried accessing the wiki by changing the yaml config:

```
host: 'http://192.168.0.333'
port: 4080
```

Still no prevail.
Even directly accessing it, via my PC (it's a headless server) gives me the same error:
```
192.168.0.333 refused to connect.
````

There is no logging from wiki.js whatsoever.
I looked on the troubleshoot page and `pm2` is not a recognized command or port, so it didn't help me either.

### Expected behavior
That I can access the wiki 

### Steps to reproduce the behavior
I guess installing it on FreeBSD?

**Comment by NGPixel** [comment]
You must install pm2 globally to be able to run pm2 commands:
```sh
# Install pm2 globally:
npm install -g pm2

# View last 100 lines of logs:
pm2 logs wiki --lines 100
```

**Comment by theAlchemist-dev** [comment]
Thank you for that, I have found some logging:

```
1|wiki     | { Error: Cannot find module './build/Release/DTraceProviderBindings'
1|wiki     |     at Function.Module._resolveFilename (module.js:489:15)
1|wiki     |     at Function.Module._load (module.js:439:25)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/dtrace-provider/dtrace-provider.js:17:23)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/bunyan/lib/bunyan.js:79:18)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/server/libs/search-index/index.js:1:78)
1|wiki     |     at Module._compile (module.js:573:30) code: 'MODULE_NOT_FOUND' }
1|wiki     | { Error: Cannot find module './build/default/DTraceProviderBindings'
1|wiki     |     at Function.Module._resolveFilename (module.js:489:15)
1|wiki     |     at Function.Module._load (module.js:439:25)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/dtrace-provider/dtrace-provider.js:17:23)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/bunyan/lib/bunyan.js:79:18)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/server/libs/search-index/index.js:1:78)
1|wiki     |     at Module._compile (module.js:573:30) code: 'MODULE_NOT_FOUND' }
1|wiki     | { Error: Cannot find module './build/Debug/DTraceProviderBindings'
1|wiki     |     at Function.Module._resolveFilename (module.js:489:15)
1|wiki     |     at Function.Module._load (module.js:439:25)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/dtrace-provider/dtrace-provider.js:17:23)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/node_modules/bunyan/lib/bunyan.js:79:18)
1|wiki     |     at Module._compile (module.js:573:30)
1|wiki     |     at Object.Module._extensions..js (module.js:584:10)
1|wiki     |     at Module.load (module.js:507:32)
1|wiki     |     at tryModuleLoad (module.js:470:12)
1|wiki     |     at Function.Module._load (module.js:462:3)
1|wiki     |     at Module.require (module.js:517:17)
1|wiki     |     at require (internal/module.js:11:18)
1|wiki     |     at Object.<anonymous> (/data/node_root/wiki.virtualalchemy.nl/server/libs/search-index/index.js:1:78)
1|wiki     |     at Module._compile (module.js:573:30) code: 'MODULE_NOT_FOUND' }
```

Does this provide any help?

**Comment by theAlchemist-dev** [comment]
Ok, so I figured out that I was the one that did something wrong. So the wiki is working now :)

I don't know though, if the error reported in the post above is important?

**Comment by topher** [comment]
@theAlchemist-dev what did you do wrong? I'm getting the same error

**Comment by theAlchemist-dev** [comment]
Hehe... I configured the proxy with a wrong port number.
Simple thing to oversee, port 4080 vs 4088.

So it was an issue with Apache, not with the wiki app :)
