### ISSUE TITLE
wikisjs with systemctl

### ISSUE THREAD

**Issue by peutre** [Requarks/wiki#2600]
**Question**

I got an error when i start to start wikijs with **systemctl**.
For info, everything is working well when i do : **node server**

**Host Info:**

OS: CentOS Linux release 7.6.1810 (Core)
Wiki.js version: 2.5.126
Database engine: postgres

**The problem :**

 **systemctl status wiki**
```
● wiki.service - Wiki.js
   Loaded: loaded (/etc/systemd/system/wiki.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since jeu. 2020-09-10 09:55:45 CEST; 1 months 9 days ago
  Process: 128376 ExecStart=/bin/node server (code=exited, status=1/FAILURE)
 Main PID: 128376 (code=exited, status=1/FAILURE)
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: Unit wiki.service entered failed state.
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: wiki.service failed.
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: wiki.service holdoff time over, scheduling restart.
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: Stopped Wiki.js.
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: start request repeated too quickly for wiki.service
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: Failed to start Wiki.js.
sept. 10 09:55:45 slql-wiki2-app1 systemd[1]: Unit wiki.service entered failed state.
```
**cat /etc/systemd/system/wiki.service**
```
[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/bin/node server
Restart=always
# Consider creating a dedicated user for Wiki.js here:
User=nobody
Environment=NODE_ENV=production
WorkingDirectory=/root/wikijs2
[Install]
WantedBy=multi-user.target
```

With **journalctl -e**, i see : 

```
oct. 20 15:05:07 slql-wiki2-app1 systemd[1]: Started Wiki.js.
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: internal/modules/cjs/loader.js:638
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: throw err;
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: ^
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: Error: Cannot find module '/root/wikijs2/server'
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: at startup (internal/bootstrap/node.js:283:19)
oct. 20 15:05:07 slql-wiki2-app1 node[79830]: at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
oct. 20 15:05:07 slql-wiki2-app1 systemd[1]: wiki.service: main process exited, code=exited, status=1/FAILURE
```
Many thanks for your help!

**Comment by jtapsl** [comment]
When you manually start using **node server** , are you testing with the same user you have specified in the systemd service file?

The service file you posted has
`User=nobody`

**Comment by peutre** [comment]
Many thanks for your help.

That's true, **node server** is executed usually under **root**

When i changed the systemd service file to : 
`User=root`
This is working well now.

But it's not a secure way if i stay like that, do you have any recommandation about the user's wikijs execution ? 
Maybe i will have to chown the wikijs directory to this futur user.

An other question about systemctl : 
```
systemctl status wiki
● wiki.service - Wiki.js
   Loaded: loaded (/etc/systemd/system/wiki.service; enabled; vendor preset: disabled)
   Active: active (running) since mer. 2020-10-21 14:44:22 CEST; 4s ago
 Main PID: 73908 (node)
   CGroup: /system.slice/wiki.service
           ├─73908 /bin/node server
           ├─73946 git remote update origin
           ├─73947 git fetch --multiple origin
           ├─73948 git fetch --append origin
           ├─73949 git-remote-https origin https://peutre:fakepassword@github.com/peutre/Wikijs.git
```

Not cool to see my git password into the systemctl process, any idea to hide that ?

**Comment by LadySmith** [comment]
Create a new user for wikijs then chown wiki folder. Had same problem, fixed it like this.

**Comment by Frankstar** [comment]
`Not cool to see my git password into the systemctl process, any idea to hide that ?`

use a key file.
is my first idea about that.

**Comment by Maxzor** [comment]
No, node server is NOT to be executed under root.
I personally run a user systemd daemon.

**Comment by peutre** [comment]
Thank you everyone, i went for a new user for a specific directory
