### ISSUE TITLE
startup problem: catch block with SyntaxError

### ISSUE THREAD

**Issue by pbg42** [Requarks/wiki#2871]
I'm just trying to get my first wiki.js (2.5.170) runnning on Ubuntu20.0.4LTS with db postgres
- created db and user
- modified config.yml
- starting node server (as root)
### Actual behavior
```
root@nas3:/data/wiki# node server
Loading configuration from /data/wiki/config.yml... OK
2020-12-27T20:51:12.495Z [MASTER] info: =======================================
2020-12-27T20:51:12.521Z [MASTER] info: = Wiki.js 2.5.170 =====================
2020-12-27T20:51:12.523Z [MASTER] info: =======================================
2020-12-27T20:51:12.524Z [MASTER] info: Initializing...
(node:24897) UnhandledPromiseRejectionWarning: /data/wiki/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/wiki/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
(node:24897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
That does not look like a normal error message that shows a newbie like me what he did wrong, so my question:

Any idea what might cause that?
Thanks in advance

**Comment by daniellivingston** [comment]
This is due to having an outdated version of Node. Run `$ node -v` and you'll see it's probably v8.x. Try installing a version of Node supported in the documentation:

1. https://docs.requarks.io/install/requirements
2. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
