### ISSUE TITLE
Lost all entries in MongoDB

### ISSUE THREAD

**Issue by adaniloff** [Requarks/wiki#313]
Hello,

I have an issue with the mongodb `entries` collection.
After restarting my server, I lost them all.
Fortunately, it doesn't impact the .md files which are still in the repo folder, but I cannot have access to them anymore since then.

### Actual behavior
```
# Running those commands on the term :
mongo
> use <my_db>
> db.entries.find()
# --> Return nothing...
```
### Expected behavior
Returning my entries ?

I tried to clean the cache from the administrator panel, but that only prompt an alert "coming soon!".
The version I'm using is the v1.0.7.

**Comment by NGPixel** [comment]
The `entries` table is only a cache and not actual content. The table is re-populated each time you start Wiki.js.

**Comment by adaniloff** [comment]
The problem is, after restarting Wiki.js, this table was not repopulated. 
So I lost all the navigation entries and I can't access to my pages unless I manually open them on the server with VIM.

Waiting for the confirmation to close the ticket would be nice too, because I'm a bit confused right now, I don't want to open another one (which obviously would be a duplicate one) but I'm not sure about continuing on this one either,

English is not my native language so please, be indulgent and try to understand my issue.
I will post a screenshot if you need one to understand the situation.

**Comment by NGPixel** [comment]
Do you have any errors in the logs / console when starting Wiki.js?

**Comment by adaniloff** [comment]
I'll check tomorrow, but I don't remember seeing any error.

**Comment by adaniloff** [comment]
Sorry, I had some personal problems since my last answer ; I can not investigate this case for the moment. I will give you the requested information as soon as I can :).

**Comment by adaniloff** [comment]
@NGPixel 
Here what I got when restarting the Wiki.
Absolutely no errors : 

adaniloff@ns3044591 ➜  wiki node wiki restart
✔ Wiki.js has stopped successfully.
✔ Wiki.js has started successfully.

The problem persists tho.

**Comment by adaniloff** [comment]
Up. The problem persist. Any idea?

**Comment by captn3m0** [comment]
Facing the same issue. Running a `mongorocks` container alongside the wiki container. Logs follow:

<details>
<summary>
docker logs wiki
</summary>

```
$ docker logs wiki
2017-12-24 08:20:14,946 CRIT Supervisor running as root (no user in config file)
2017-12-24 08:20:14,952 INFO RPC interface 'supervisor' initialized
2017-12-24 08:20:14,952 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-24 08:20:14,952 INFO supervisord started with pid 1
2017-12-24 08:20:15,954 INFO spawned: 'wikijs' with pid 8
2017-12-24 08:20:17,167 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-12-24 08:20:19,182 INFO reaped unknown pid 32
2017-12-24 13:27:03,598 WARN received SIGTERM indicating exit request
2017-12-24 13:27:03,608 INFO waiting for wikijs to die
2017-12-24 13:27:06,743 INFO waiting for wikijs to die
2017-12-24 13:27:09,442 INFO reaped unknown pid 36
2017-12-24 13:27:10,453 INFO waiting for wikijs to die
2017-12-24 13:27:13,456 INFO waiting for wikijs to die
2017-12-24 13:28:02,995 CRIT Supervisor running as root (no user in config file)
Unlinking stale socket /var/run/supervisor.sock
2017-12-24 13:28:03,437 INFO RPC interface 'supervisor' initialized
2017-12-24 13:28:03,437 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-24 13:28:03,437 INFO supervisord started with pid 1
2017-12-24 13:28:04,439 INFO spawned: 'wikijs' with pid 9
2017-12-24 13:28:05,441 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-12-24 13:28:15,437 INFO reaped unknown pid 33
2017-12-25 09:38:08,261 WARN received SIGTERM indicating exit request
2017-12-25 09:38:08,363 INFO waiting for wikijs to die
2017-12-25 09:38:10,592 INFO reaped unknown pid 37
2017-12-25 09:38:11,626 INFO waiting for wikijs to die
2017-12-25 09:38:14,630 INFO waiting for wikijs to die
2017-12-25 09:38:17,634 INFO waiting for wikijs to die
2017-12-25 09:38:30,362 CRIT Supervisor running as root (no user in config file)
Unlinking stale socket /var/run/supervisor.sock
2017-12-25 09:38:30,888 INFO RPC interface 'supervisor' initialized
2017-12-25 09:38:30,888 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-25 09:38:30,889 INFO supervisord started with pid 1
2017-12-25 09:38:31,893 INFO spawned: 'wikijs' with pid 9
2017-12-25 09:38:32,896 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-12-25 09:38:53,537 INFO reaped unknown pid 33
2017-12-25 09:41:32,750 WARN received SIGTERM indicating exit request
2017-12-25 09:41:32,750 INFO waiting for wikijs to die
2017-12-25 09:41:34,085 INFO reaped unknown pid 37
2017-12-25 09:41:36,093 INFO waiting for wikijs to die
2017-12-25 09:41:39,096 INFO waiting for wikijs to die
2017-12-25 09:41:42,100 INFO waiting for wikijs to die
2017-12-25 09:42:16,267 CRIT Supervisor running as root (no user in config file)
Unlinking stale socket /var/run/supervisor.sock
2017-12-25 09:42:16,596 INFO RPC interface 'supervisor' initialized
2017-12-25 09:42:16,596 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-25 09:42:16,596 INFO supervisord started with pid 1
2017-12-25 09:42:17,607 INFO spawned: 'wikijs' with pid 8
2017-12-25 09:42:18,609 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-12-25 09:42:31,617 INFO reaped unknown pid 32
```
</details>


<details>
<summary>
wiki-stderr.log
</summary>

```
2017-12-18T18:33:33.454Z - error: [AGENT] Git remote error!
Unhandled rejection TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at fs.mkdirAsync.catch.then.then (/var/wiki/server/libs/git.js:102:24)
    at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/wiki/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
2017-12-18T18:33:34.397Z - error: [AGENT] Unable to fetch from git origin!
2017-12-18T18:33:34.397Z - error: [AGENT] Unable to push changes to remote Git repository!
2017-12-18T18:33:34.397Z - error: [AGENT] One or more jobs have failed:  
{ code: 1,
  message: '`git --git-dir=/repo/.git --work-tree=/repo pull origin master` failed with code 1',
  stderr: 'fatal: could not read Username for \'https://github.com\': No such device or address\n',
  stdout: '' }
```
</details>


<details>
<summary>
wiki-stdout.log
</summary>

```
2017-11-27T05:13:33.333Z - info: [SERVER] Wiki.js is initializing...
2017-11-27T05:13:33.775Z - info: [SERVER] Checking data directories...
2017-11-27T05:13:33.798Z - info: [SERVER] Data and Repository directories are OK.
2017-11-27T05:13:34.833Z - info: [SERVER] Checking Git repository...
2017-11-27T05:13:39.049Z - info: [SERVER] Starting HTTP/WS server on port 9999...
2017-11-27T05:13:39.151Z - info: [SERVER] HTTP/WS server started successfully! [RUNNING]
2017-11-27T05:13:39.349Z - info: [SERVER] Search index flushed and ready.
2017-11-27T05:13:39.526Z - info: [SERVER] Git repository is OK.
2017-11-27T05:13:39.656Z - info: [AGENT] Background Agent is initializing...
2017-11-27T05:13:41.386Z - info: [AGENT] Checking Git repository...
2017-11-27T05:13:43.101Z - info: [AGENT] Running all jobs...
2017-11-27T05:13:43.101Z - info: [AGENT] Performing pull from remote Git repository...
2017-11-27T05:13:43.176Z - info: [AGENT] Git repository is OK.
2017-11-27T05:16:15.294Z - info: [SERVER] - SHUTTING DOWN - Terminating Background Agent...
2017-11-27T05:16:15.294Z - info: [SERVER] - SHUTTING DOWN - Performing git sync...
2017-11-27T05:16:15.295Z - info: [SERVER] Performing pull from remote Git repository...
```
</details>

- The mongoDB server has had unclean shutdowns, but is able to recover data I think.
- After I edit and save a document, it starts appearing in the list. (@adaniloff do you see the same behaviour?)
- Will try to see if a clean shutdown on mongoDB also causes this.

**Comment by Ruffeng** [comment]
Here the same problem, deployed on heroku directly through the other repo.

**Comment by captn3m0** [comment]
As per the latest README, MongoDB is being phased out for postgres + Redis.

I'd have liked to just see a small local KV store (like rocksDB/SQLite) personally, but I'm sure there are good reasons.

Seeing the milestone however, not expecting any fixes on this front.

**Comment by NGPixel** [comment]
@captn3m0 SQLite may be possible (or MySQL or SQL Server for that matter) as 2.0 is using the Sequelize ORM, which supports all of them.

However the focus is on postgreSQL for now. Keep in mind that switching to SQLite means no search capability, or very limited.

**Comment by adaniloff** [comment]
For information, I've fixed the issue doing this :
- backuping the repo folder
- removing entirely the project
- reinstalling it at its latest version 
- putting the repo folder in the new project

This is a short term hack/fix which does not solve the initial pb, but at least your service will be available again.

Hope this help.
