### ISSUE TITLE
upload file error

### ISSUE THREAD

**Issue by May-Yaha** [Requarks/wiki#3160]
[{"errors":[{"message":"with recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFolders` where `id` = 0 union select `a`.`id`, `a`.`name`, `a`.`slug`, `a`.`parentId` from `assetFolders` as `a` inner join `ancestors` on `ancestors`.`parentId` = `a`.`id`) select * from `ancestors` - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFol' at line 1","locations":[{"line":3,"column":5}],"path":["assets","list"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFol' at line 1","stacktrace":["Error: with recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFolders` where `id` = 0 union select `a`.`id`, `a`.`name`, `a`.`slug`, `a`.`parentId` from `assetFolders` as `a` inner join `ancestors` on `ancestors`.`parentId` = `a`.`id`) select * from `ancestors` - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFol' at line 1","    at Packet.asError (/home/work/apps/wiki/node_modules/mysql2/lib/packets/packet.js:712:17)","    at Query.execute (/home/work/apps/wiki/node_modules/mysql2/lib/commands/command.js:28:26)","    at Connection.handlePacket (/home/work/apps/wiki/node_modules/mysql2/lib/connection.js:425:32)","    at PacketParser.onPacket (/home/work/apps/wiki/node_modules/mysql2/lib/connection.js:75:12)","    at PacketParser.executeStart (/home/work/apps/wiki/node_modules/mysql2/lib/packet_parser.js:75:16)","    at Socket.<anonymous> (/home/work/apps/wiki/node_modules/mysql2/lib/connection.js:82:25)","    at Socket.emit (node:events:378:20)","    at addChunk (node:internal/streams/readable:313:12)","    at readableAddChunk (node:internal/streams/readable:288:9)","    at Socket.Readable.push (node:internal/streams/readable:227:10)","    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"]}}}],"data":{"assets":{"list":null,"__typename":"AssetQuery"}}}]

**Comment by May-Yaha** [comment]
https://github.com/Requarks/wiki/issues/2149
