### ISSUE TITLE
Pages don't show last revision (GraphQL error: Cannot return null for non-nullable field ResponseStatus.slug.)

### ISSUE THREAD

**Issue by missytake** [Requarks/wiki#3196]
**Describe the bug**
If I edit and save a page, it throws the following error in the webUI: `GraphQL error: Cannot return null for non-nullable field ResponseStatus.slug.`. It aborts saving, I have to close the edit view manually. The page looks the same as before I tried to change it, but if I look at the page history, my changes *do* appear. So it just doesn't seem to show the last revision.

Also, sometimes if I try to click on "Save" during editing, it alerts me of a conflict, where I can choose between the local and the remote version, even if there are no differences between them. It says the local version is editable, while the remote version is write-protected. I'm not sure whether this is expected or not.

**To Reproduce**
1. Go to a page, click on edit
2. Make some changes
3. Click on "Save"
4. See error: `GraphQL error: Cannot return null for non-nullable field ResponseStatus.slug.`
5. Click on "Close", confirm that you want to discard changes
6. See that the page is unchanged.
7. Click on the revision history
8. See that all unsuccessful "Save" attempts are indeed written into the history.

**Expected behavior**
I expect that if I save a page, the changes are displayed, and that a page always shows the last revision.

**Screenshots**
If applicable, add screenshots to help explain your problem:

![Screenshot_2021-03-10_08-59-19](https://user-images.githubusercontent.com/57442838/110596080-28300f00-817f-11eb-8e21-4e4c1a656421.png)

![Screenshot_2021-03-10_08-59-31](https://user-images.githubusercontent.com/57442838/110596089-2b2aff80-817f-11eb-82e2-6209c491afff.png)

**Host Info (please complete the following information):**
 - OS: openBSD 6.8
 - Wiki.js version: 2.5.170
 - Database engine: sqlite

**Additional context**
- Browser: Firefox 86.0, reproducible in a private window
- Client OS: Xubuntu 20.04

**Comment by missytake** [comment]
If I retry the faulty request with curl, I get the following response:

```
[
  {
    "errors": [
      {
        "message": "Cannot return null for non-nullable field ResponseStatus.slug.",
        "locations": [
          {
            "line": 7,
            "column": 9
          }
        ],
        "path": [
          "pages",
          "update",
          "responseResult",
          "slug"
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "Error: Cannot return null for non-nullable field ResponseStatus.slug.",
              "    at completeValue (/srv/wiki/node_modules/graphql/execution/execute.js:595:13)",
              "    at completeValueCatchingError (/srv/wiki/node_modules/graphql/execution/execute.js:530:19)",
              "    at resolveField (/srv/wiki/node_modules/graphql/execution/execute.js:461:10)",
              "    at executeFields (/srv/wiki/node_modules/graphql/execution/execute.js:297:18)",
              "    at collectAndExecuteSubfields (/srv/wiki/node_modules/graphql/execution/execute.js:748:10)",
              "    at completeObjectValue (/srv/wiki/node_modules/graphql/execution/execute.js:738:10)",
              "    at completeValue (/srv/wiki/node_modules/graphql/execution/execute.js:626:12)",
              "    at completeValue (/srv/wiki/node_modules/graphql/execution/execute.js:592:21)",
              "    at completeValueCatchingError (/srv/wiki/node_modules/graphql/execution/execute.js:530:19)",
              "    at resolveField (/srv/wiki/node_modules/graphql/execution/execute.js:461:10)",
              "    at executeFields (/srv/wiki/node_modules/graphql/execution/execute.js:297:18)",
              "    at collectAndExecuteSubfields (/srv/wiki/node_modules/graphql/execution/execute.js:748:10)",
              "    at completeObjectValue (/srv/wiki/node_modules/graphql/execution/execute.js:738:10)",
              "    at completeValue (/srv/wiki/node_modules/graphql/execution/execute.js:626:12)",
              "    at /srv/wiki/node_modules/graphql/execution/execute.js:527:16",
              "    at runMicrotasks (<anonymous>)",
              "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
              "    at async Promise.all (index 0)"
            ]
          }
        }
      }
    ],
    "data": {
      "pages": {
        "update": null,
        "__typename": "PageMutation"
      }
    }
  }
]
```
