### ISSUE TITLE
git error spawn git ENOENT

### ISSUE THREAD

**Issue by lukaspupkalipinski** [Requarks/wiki#321]
### Actual behavior
Since today i get the error:
2017-11-17T12:48:38.269Z - error: [SERVER]  Error: spawn git ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

git should be not used but is installed with version:
1 logs]# git --version
git version 2.15.0

This was working as i installed it. But today something changed.
logs]# echo $PATH
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/git/bin:/root/bin

If i run node wiki.js configure, the configure screen detect no issues

**Comment by NGPixel** [comment]
Even if you don't use git remote sync, git is still required.

Wiki.js is unable to find the git executable in your path, which is why it fails.

**Comment by lukaspupkalipinski** [comment]
solved.
I reinstalled git. now it works
