### ISSUE TITLE
Git sync - file from git is not present

### ISSUE THREAD

**Issue by ronnicek** [Requarks/wiki#338]
### Actual behavior
1. Push some new file to git
2. Wait for sync
3. Check if file is in Wiki

### Expected behavior
1. Push
2. Sync
3. See the file in wiki

### Steps to reproduce the behavior
1. Setup docker-compose setup
2. Create repo with SSH key
3. Configure wiki to get files from git (https://github.com/ronnicek/testdocs)
4. Create new file in github and push it to repo

Error log:
```
2017-11-29T23:40:01.478Z - error: [AGENT]  OperationalError: Entry filecreatedingithub does not exist!
    at fs.statAsync.then.catch (/var/wiki/server/libs/entries.js:164:13)
    at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/wiki/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
2017-11-29T23:40:01.482Z - error: [AGENT]  TypeError: Cannot read property 'title' of undefined
    at self.fetchOriginal.catch.then.catch.then (/var/wiki/server/libs/entries.js:264:29)
    at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/wiki/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/wiki/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:689:18)
```

**Comment by ronnicek** [comment]
Tried to add headers to file, but still the same

```
<!-- TITLE: File from github -->
<!-- SUBTITLE: A SUMMARY! -->
```

**Comment by NGPixel** [comment]
Make sure the file respects the kebab-case standard. (lowercase, words and numbers separated by an hyphen).

**Comment by ronnicek** [comment]
Ah, working now :) thanks!
