### ISSUE TITLE
Playing with v2

### ISSUE THREAD

**Issue by moonmeister** [Requarks/wiki#391]
### Actual behavior
I'm playing around with v2. My company is looking for a wiki solution and v1 doesn't meet our needs. I know v2 isn't ready for prime time but I was hoping to see if it'll meet our needs and we can be patient. 

I made it through lots of hoops but I'm currently stuck at the login page. It'll let me login and says it was successful but then doesn't open a home page...really do anything. Side note the strings are filled too. (see screenshot below). 

If this is "expected" that's fine but I'm assuming I'm unaware of some issue.

please help, here's the one error I'm seeing in the cli:

```
Error: Invalid locale or namespace
    at Object.getByNamespace (/home/user/wiki/server/modules/localization.js:40:13)
    at translations (/home/user/wiki/server/schemas/resolvers-translation.js:7:24)
    at resolveFieldValueOrError (/home/user/wiki/node_modules/graphql/execution/execute.js:544:18)
    at resolveField (/home/user/wiki/node_modules/graphql/execution/execute.js:508:16)
    at /home/user/wiki/node_modules/graphql/execution/execute.js:357:18
    at Array.reduce (<anonymous>)
    at executeFields (/home/user/wiki/node_modules/graphql/execution/execute.js:354:42)
    at executeOperation (/home/user/wiki/node_modules/graphql/execution/execute.js:278:122)
    at executeImpl (/home/user/wiki/node_modules/graphql/execution/execute.js:142:14)
    at Object.execute (/home/user/wiki/node_modules/graphql/execution/execute.js:119:229)
    at doRunQuery (/home/user/wiki/node_modules/apollo-server-core/dist/runQuery.js:98:42)
    at /home/user/wiki/node_modules/apollo-server-core/dist/runQuery.js:22:54
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

<img width="496" alt="screen shot 2018-01-31 at 5 16 31 pm" src="https://user-images.githubusercontent.com/2730871/35656168-a2a046f4-06aa-11e8-9fea-7dff9007745b.png">

### Expected behavior

Strings fill out and I can actually login.

### Steps to reproduce the behavior

cloned git repo

checkout dev branch

yarn install

yarn build

install postgres and create db + user

install redis

yarn run dev

go through config

--it does something weird--

confirm config looks good

kill server

yarn run dev

login loads 

--issues--

**Comment by NGPixel** [comment]
2.0 is not ready and not in a usable state.
