### ISSUE TITLE
How can I change the styling?

### ISSUE THREAD

**Issue by tikhbana** [Requarks/wiki#425]
I've added a color to the "client/scss/base/colors.scss" and tried to compile it using "yarn run build" but it returns:

Error: Cannot find module 'colors/safe'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tikh/Documents/wiki/tools/fuse.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tikhbana** [comment]
I've also tried replacing a color, I get an error: 

Errors for configure bundle
 → ERROR Undefined variable: “$key”.

**Comment by NGPixel** [comment]
You must install dependencies first:

`yarn install`

**Comment by tikhbana** [comment]
Got it! :+1: 

I'm trying to change the colors, so I just replaced the hex codes to see if that would work, but I'm getting this:

  → WARNING Statement "package.js" has failed to resolve in module "got"
  → WARNING Statement "dist/clipboard-action.js" has failed to resolve in module "vue-clipboards"

**Comment by NGPixel** [comment]
You can ignore these warnings.
