### ISSUE TITLE
LDAP bind fails

### ISSUE THREAD

**Issue by straubr** [Requarks/wiki#427]
I'm terrible sorry if this is a stupid mistake on my side:

We're unable to auth via ldap. Our config.yml looks like this:

  ldap:
    enabled: true
    url: "ldap://xxx.xxx.xxx.xxx:389"
    bindDN: "CN=UserName,OU=OU2,OU=OU1,DC=site,DC=com"
    bindCredentials: "Password"
    searchBase: "ou=UserOU, dc=site, dc=com"
    searchFilter: "(samaccountname={{username}})"
    tlsEnabled: false

With these settings I can successfully auth with ldapauth-pass with this express example:
https://github.com/vesse/passport-ldapauth

When trying to login to wiki js, we receive this error on the frontend:
000004DC: LdapErr: DSID-0C09075A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1

Could you hint me what I was doing wrong, and / or where I can find and enable debug logs for ldap auth?

Many thanks and best regards,
Rolf

**Comment by NGPixel** [comment]
Wiki.js is using passport-ldapauth. If it works directly with the library, there's no reason it shouldn't work in Wiki.js as the config is passed to the library directly with no modifications.

Read my answer on this post to get more debugging info:
https://github.com/Requarks/wiki/issues/360#issuecomment-353826447

**Comment by straubr** [comment]
I'm really stumped here. passport-ldapauth recommends to use ldapsearch to debug / analyze connections. I can successfully use this command:
ldapsearch -H ldap://xxx.xxx.xxx.xxx:389 -x -D "CN=Wiki JS, [FullPathToCN]" -w secret -b "[FullPathToSearchBase]" "(samaccountname=[MySamAccount])"
with the same values as in config.yml and I receive exactly 1 hit (as expected):

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

Using exactly those values in the config.yml (well, with the {{username}} placeholder), yields:
000004DC: LdapErr: DSID-0C09075A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1

When using the debug file auth.js provided by you, the logs throw:

2018-03-05T10:46:43.841Z - info: [SERVER] ATTEMPTING LDAP AUTHENTICATION...

==> logs/wiki-error-0.log <==
2018-03-05T10:46:46.883Z - error: [SERVER]  OperationsError: 000004DC: LdapErr: DSID-0C09075A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1
    at messageCallback (/opt/wiki.js/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/opt/wiki.js/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.write (/opt/wiki.js/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/opt/wiki.js/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

and the frontend changes to:
Failed to serialize user into session

**Comment by straubr** [comment]
Allright. It was a stupid mistake on my side.

For whatever reason I was having "bindDN" in my config (notice the capital 'N'). The proper keyword is however "bindDn".

Sorry for this and thanks for the great software!

**Comment by straubr** [comment]
As a side-note:

Using passport-ldapauth from a standalone script, the parameter "bindDN" is working.
