### ISSUE TITLE
Uploading file fails. Error is 'Unsupported file type: undefined'

### ISSUE THREAD

**Issue by tylerjgarland** [Requarks/wiki#433]
### Actual behavior
Upload image fails. File is uploaded to server, but wiki file browser doesn't display it. 
Log displays this error:

Unhandled rejection TypeError: unsupported file type: undefined (file: /root/repo/uploads/2-a-2-d-31870-e-014473-a-70-e-382316825-b-4-c.jpg)
    at lookup (/root/node_modules/image-size/lib/index.js:34:9)
    at /root/node_modules/image-size/lib/index.js:93:22
    at /root/node_modules/image-size/lib/index.js:50:9
    at /root/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)

### Expected behavior
File to be uploaded
### Steps to reproduce the behavior
Upload any file.

**Comment by tylerjgarland** [comment]
I notice if I restart the wiki service the files will then show up.
