### ISSUE TITLE
Error when launched

### ISSUE THREAD

**Issue by PurgingPanda** [Requarks/wiki#46]
Installed using: npm install wiki.js@latest

```
TypeError: Cannot supply flags when constructing one RegExp from another
    at new RegExp (native)
    at Object.<anonymous> (/root/wikijs/libs/markdown.js:70:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/wikijs/server.js:39:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Object.<anonymous> (/root/wiki/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by NGPixel** [comment]
Thanks, fixed for Beta 9.
