### ISSUE TITLE
docker-compose: empty reply from server

### ISSUE THREAD

**Issue by kingfisher77** [Requarks/wiki#529]
### Actual behavior

Using default settings from documentation for config.yml and docker-compose.yml results in:

```
$ curl localhost:80
curl: (52) Empty reply from server

```

### Expected behavior

Should load the page.

### Steps to reproduce the behavior

Docker images are up and running:

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                  NAMES
42b3f347852f        requarks/wiki:latest   "supervisord --nodae…"   6 minutes ago       Up 6 minutes        0.0.0.0:80->3000/tcp   wiki_wikijs_1
a599d342994f        mongo                  "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        27017/tcp              wiki_wikidb_1
```

**Comment by NGPixel** [comment]
Bind the container folder `/logs` to look for errors.

**Comment by kingfisher77** [comment]
Something with the connection to mongo?
```
==> logs/supervisord.log <==
2018-05-21 19:17:39,802 CRIT Supervisor running as root (no user in config file)
2018-05-21 19:17:39,820 INFO RPC interface 'supervisor' initialized
2018-05-21 19:17:39,821 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-05-21 19:17:39,822 INFO supervisord started with pid 1
2018-05-21 19:17:40,829 INFO spawned: 'wikijs' with pid 7
2018-05-21 19:17:42,549 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

==> logs/wiki-stderr.log <==
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

==> logs/wiki-stdout.log <==
2018-05-21T19:17:41.292Z - info: [SERVER] Checking data directories...
2018-05-21T19:17:41.293Z - info: [SERVER] Data and Repository directories are OK.
2018-05-21T19:17:41.546Z - info: [SERVER] Checking Git repository...
2018-05-21T19:17:42.627Z - info: [SERVER] Starting HTTP/WS server on port 80...
2018-05-21T19:17:42.657Z - info: [SERVER] HTTP/WS server started successfully! [RUNNING]
2018-05-21T19:17:42.738Z - info: [SERVER] Search index flushed and ready.
2018-05-21T19:17:42.788Z - info: [SERVER] Git repository is OK.
2018-05-21T19:17:42.812Z - info: [AGENT] Background Agent is initializing...
2018-05-21T19:17:43.353Z - info: [AGENT] Checking Git repository...
2018-05-21T19:17:43.965Z - info: [AGENT] Git repository is OK.
```

**Comment by NGPixel** [comment]
List more lines from the `wiki-stderr.log` but yes it looks like a mongo connection issue

**Comment by kingfisher77** [comment]
Sorry, it was a tail output. Here is the full log:
 
```
2018-05-21T19:17:42.728Z - ^[[31merror^[[39m: [SERVER] Failed to connect to MongoDB instance.
Unhandled rejection MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled rejection MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-05-21T19:17:43.927Z - ^[[31merror^[[39m: [AGENT] Failed to connect to MongoDB instance.
Unhandled rejection MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by NGPixel** [comment]
Your mongodb is in another container, so you cannot use `localhost` to connect to it. Use the hostname provided for the mongo container. In the example docker-compose, this would be `wikidb:27017`

**Comment by kingfisher77** [comment]
Yes, it is working now. Thank you!

Maybe you want to adjust the sample docker-compose file. So that the setup is working from th scratch without modifying. https://github.com/Requarks/wiki/blob/master/config.sample.yml
