### ISSUE TITLE
'Cannot read property '0' of null' in markdown.js

### ISSUE THREAD

**Issue by DeaDCaTsSociety** [Requarks/wiki#534]
When I edit document, suddenly error popup occured.
after error, I can't access that page I edited and can't see that page in all pages.
so I create same name document but wiki told me that page already created but I can't access.

if I type url that page, this error occured 

```
TeX parse error: You can't use 'macro parameter character #' in math mode
Error: TypeError: Cannot read property '0' of null
    at mathjax.typeset.result (/home/deadcat/wiki/server/libs/markdown.js:341:37)
    at ReturnResult (/home/deadcat/wiki/node_modules/mathjax-node/lib/main.js:782:3)
    at Function.execute (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Function.WAITEXECUTE (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/deadcat/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
```

**Comment by NGPixel** [comment]
Disable mathjax in your `config.yml` and restart wiki.js:

```yaml
features:
  mathjax: false
```
