### ISSUE TITLE
Certificate Issue with binding to LDAP 

### ISSUE THREAD

**Issue by lukeshaughnessy** [Requarks/wiki#536]
When logging in with an LDAP account, this error is displayed:

`Failed to serialize user into session
Oops, something went wrong`

I have added the debug auth.js file mentioned here:
https://github.com/Requarks/wiki/issues/360#issuecomment-353826447

Error logs show this:

2018-05-31T10:29:28.873Z - error: [SERVER]  Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)

TLS is disabled in config.yml, so I'm not sure why it's complaining about certificates.

Any ideas?

**Comment by NGPixel** [comment]
Even if you set TLS to false in the config, make sure the ldap controller you are connecting to doesn't require TLS itself.
