### ISSUE TITLE
existing files from git repository are not showing up in the console

### ISSUE THREAD

**Issue by vedarthk** [Requarks/wiki#543]
### Actual behavior
If the file is not present in the applications database but if it is present in the git repo, the app throws following error (`test-file` is the name of the file):

```
wikijs_1  | 2018-06-06T14:40:02.866Z - error: [AGENT]  OperationalError: Entry test-file does not exist!
wikijs_1  |     at fs.statAsync.then.catch (/var/wiki/server/libs/entries.js:164:13)
wikijs_1  |     at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
wikijs_1  |     at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
wikijs_1  |     at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
wikijs_1  |     at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
wikijs_1  |     at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:689:18)
wikijs_1  |     at Async._drainQueue (/var/wiki/node_modules/bluebird/js/release/async.js:133:16)
wikijs_1  |     at Async._drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:143:10)
wikijs_1  |     at Immediate.Async.drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:17:14)
wikijs_1  |     at runCallback (timers.js:789:20)
wikijs_1  |     at tryOnImmediate (timers.js:751:5)
wikijs_1  |     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Expected behavior
If there are files in git repository it should be shown as a page in the console as per the documentation

https://docs.requarks.io/wiki/install/installation/git#why-do-i-need-it

I am trying to migrate my existing documentation to this application, let me know if I am missing anything.

### Steps to reproduce the behavior
Add a file to git repo and restart the application

**Comment by NGPixel** [comment]
Make sure your files follow the snake case format (some-file.md).
