### ISSUE TITLE
Node won't start on fresh install latest sync from dev

### ISSUE THREAD

**Issue by geraldsnm** [Requarks/wiki#548]
Running:

node wiki configure

(Tried with and without a config file present)

/usr/local/wiki.js/wiki.js:10
const init = require('./server/init')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

Fresh install on Centos 6 x86_64:

Linux wiki.sys.*.com 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

node --version
v0.10.48

git --version
git version 2.10.5

/usr/local/mongodb/bin/mongo --version
MongoDB shell version v3.6.5
git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel62
    distarch: x86_64
    target_arch: x86_64

I tried using the install.sh from -
curl -sSo- https://wiki.js.org/install.sh | bash

As well as installing using npm -

npm install wiki.js@latest

Running npm install results in the following error, looks like all deps won't install:

1285 error TypeError: Cannot read property 'latest' of undefined
1285 error     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
1285 error     at /usr/lib/node_modules/npm/lib/cache.js:675:5
1285 error     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
1285 error     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
1285 error     at FSReqWrap.oncomplete (fs.js:171:20)
1286 error If you need help, you may report this log at:
1286 error     <http://github.com/isaacs/npm/issues>
1286 error or email it to:
1286 error     <npm-@googlegroups.com>
1287 error System Linux 2.6.32-696.30.1.el6.x86_64
1288 error command "/usr/local/bin/node" "/usr/bin/npm" "install"
1289 error cwd /usr/local/wiki.js
1290 error node -v v10.4.1
1291 error npm -v 1.3.6
1292 verbose exit [ 1, true ]

**Comment by geraldsnm** [comment]
Nevermind - please disregard - the version of Node was too old - downloading from the latest from nodesource.com fixed the issue!

Thanks
