### ISSUE TITLE
Return 503 error after creating new page

### ISSUE THREAD

**Issue by ryanlee2014** [Requarks/wiki#598]
English is not my mother tongue; please excuse any errors on my part.

### Actual behavior
Wiki.js return 503 error
### Expected behavior
Display new content
### Steps to reproduce the behavior
I write something include KaTeX code in my page like this:
```
令 $d$ 等于 $\left \lfloor \log_2(r - l + 1) \right \rfloor$，我们可以用两个操作 $(l, l + 2^d - 1, v)$ 和 $(r - 2^d + 1, r, v)$ 替换此操作。正如RMQ查询过程中把一个区间分成两份一样。(详见算法竞赛入门经典--训练指南P198)
求log的操作应该预处理出log表

然后我们反过来把最大值向长度为1的区间进行合并，这个过程是$\mathcal O(nlogn)$的

最后$\mathcal O(n)$扫一遍长度为0的区间即可。
```
Then I got error and I could't open the page which I created just now.

and here is the logs after I run `pm2 logs wiki --lines 100`

```2|wiki     |     at listOnTimeout (timers.js:251:5)
2|wiki     |     at Timer.processTimers (timers.js:211:10)
2|wiki     | (node:14898) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
2|wiki     | TeX parse error: Missing superscript or subscript argument
2|wiki     | Error: TypeError: Cannot read property '0' of null
2|wiki     |     at mathjax.typeset.result (/home/ws/wiki.js/server/libs/markdown.js:341:37)
2|wiki     |     at ReturnResult (/home/ws/wiki.js/node_modules/mathjax-node/lib/main.js:782:3)
2|wiki     |     at Function.execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:243:26)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:426:36)
2|wiki     |     at Object.loadComplete (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:968:35)
2|wiki     |     at file:///home/ws/wiki.js/node_modules/mathjax/unpacked/jax/output/SVG/fonts/STIX-Web/Variants/Italic/Main.js?V=2.7.1:65:14
2|wiki     |     at Script.runInContext (vm.js:102:20)
2|wiki     |     at Object.runInContext (vm.js:280:6)
2|wiki     |     at processJavaScript (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
2|wiki     |     at HTMLScriptElementImpl._eval (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
2|wiki     |     at /home/ws/wiki.js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
2|wiki     | TeX parse error: Missing superscript or subscript argument
2|wiki     | Error: TypeError: Cannot read property '0' of null
2|wiki     |     at mathjax.typeset.result (/home/ws/wiki.js/server/libs/markdown.js:341:37)
2|wiki     |     at ReturnResult (/home/ws/wiki.js/node_modules/mathjax-node/lib/main.js:782:3)
2|wiki     |     at Function.execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:243:26)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:426:36)
2|wiki     |     at Object.loadComplete (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:968:35)
2|wiki     |     at file:///home/ws/wiki.js/node_modules/mathjax/unpacked/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main.js?V=2.7.1:574:14
2|wiki     |     at Script.runInContext (vm.js:102:20)
2|wiki     |     at Object.runInContext (vm.js:280:6)
2|wiki     |     at processJavaScript (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
2|wiki     |     at HTMLScriptElementImpl._eval (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
2|wiki     |     at /home/ws/wiki.js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
2|wiki     | (node:15265) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
2|wiki     | TeX parse error: Missing superscript or subscript argument
2|wiki     | Error: TypeError: Cannot read property '0' of null
2|wiki     |     at mathjax.typeset.result (/home/ws/wiki.js/server/libs/markdown.js:341:37)
2|wiki     |     at ReturnResult (/home/ws/wiki.js/node_modules/mathjax-node/lib/main.js:782:3)
2|wiki     |     at Function.execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:243:26)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:426:36)
2|wiki     |     at Object.loadComplete (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:968:35)
2|wiki     |     at file:///home/ws/wiki.js/node_modules/mathjax/unpacked/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main.js?V=2.7.1:574:14
2|wiki     |     at Script.runInContext (vm.js:102:20)
2|wiki     |     at Object.runInContext (vm.js:280:6)
2|wiki     |     at processJavaScript (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
2|wiki     |     at HTMLScriptElementImpl._eval (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
2|wiki     |     at /home/ws/wiki.js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
2|wiki     | TeX parse error: Missing superscript or subscript argument
2|wiki     | Error: TypeError: Cannot read property '0' of null
2|wiki     |     at mathjax.typeset.result (/home/ws/wiki.js/server/libs/markdown.js:341:37)
2|wiki     |     at ReturnResult (/home/ws/wiki.js/node_modules/mathjax-node/lib/main.js:782:3)
2|wiki     |     at Function.execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:243:26)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Process (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:495:38)
2|wiki     |     at Object.call (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:508:37)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Function.WAITEXECUTE (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:348:50)
2|wiki     |     at cb (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:225:59)
2|wiki     |     at Object.Execute (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:426:36)
2|wiki     |     at Object.loadComplete (file:///home/ws/wiki.js/node_modules/mathjax/unpacked/MathJax.js:968:35)
2|wiki     |     at file:///home/ws/wiki.js/node_modules/mathjax/unpacked/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main.js?V=2.7.1:574:14
2|wiki     |     at Script.runInContext (vm.js:102:20)
2|wiki     |     at Object.runInContext (vm.js:280:6)
2|wiki     |     at processJavaScript (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
2|wiki     |     at HTMLScriptElementImpl._eval (/home/ws/wiki.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
2|wiki     |     at /home/ws/wiki.js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
```

**Comment by NGPixel** [comment]
The TeX parser is known to have a few issues. This will be revisited in version 2.1 so hopefully the bug you're having will be fixed.
