### ISSUE TITLE
Background Agent.js is not running

### ISSUE THREAD

**Issue by linkdragon70** [Requarks/wiki#624]
### Actual behavior

The background .js agent does not run every five minutes as expected in the servers / agent.js file.
(According to the output logs)

### Expected behavior

Synchronization is done every five minutes by the .js agent

### Steps to reproduce the behavior

Install:
- git --version 2.18.0
- node -v 8.11.4
- node wiki.js --version 1.0.78

- Disable mathjax on the config.yml file

Using a Master Branch on gitlab. 

Using wiki.js on ubuntu server 16.04 ( node wiki start / stop) in a unprivileged LXC on Proxmox

###

There are no errors in the error log file, I tried several solutions, such as using previous git versions or even trying out with another GIT server. The error is persistent.

###

The only way to sync with my remote branch is to restart the wiki.js server or to manually do **git pull origin master** and **git push origin master**.

**Comment by NGPixel** [comment]
Run wiki.js in interactive mode and look for errors: `node server`

**Comment by linkdragon70** [comment]
Hello @NGPixel ,
Thank you for your reply! By performing the node server command, the agent.js seems to work properly, but when the wiki.js is started, the log files show that the agent.js is not rolling.

**Comment by linkdragon70** [comment]
I confirm, with the node server command, the agent.js works fine, but with the node wiki.js start command, the agent.js does not work. I made changes and after 1 hour no push / pull was done

**Comment by atlemagnussen** [comment]
I also experience this problem, it syncs when just started and then I get get this:
2018-09-14T18:35:23.864Z - info: [AGENT] Git Push skipped. Repository is already in sync.
now 12 hours have passed and it has not started syncing again

**Comment by atlemagnussen** [comment]
I also get this log consistantly in the error log
```
tail wiki-error-0.log
    at Function.WAITEXECUTE (file:///home/atle/wiki/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///home/atle/wiki/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Execute (file:///home/atle/wiki/node_modules/mathjax/unpacked/MathJax.js:426:36)
    at Object.loadComplete (file:///home/atle/wiki/node_modules/mathjax/unpacked/MathJax.js:968:35)
    at file:///home/atle/wiki/node_modules/mathjax/unpacked/jax/element/mml/optable/GeneralPunctuation.js?V=2.7.1:40:16
    at file:///home/atle/wiki/node_modules/mathjax/unpacked/jax/element/mml/optable/GeneralPunctuation.js?V=2.7.1:42:3
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at processJavaScript (/home/atle/wiki/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (/home/atle/wiki/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
```

**Comment by NGPixel** [comment]
@atlemagnussen Try disabling mathjax in your config.yml and restart Wiki.js
