### ISSUE TITLE
Does not appear to be bound to a port after install

### ISSUE THREAD

**Issue by mkunkel** [Requarks/wiki#63]
I have attempted installation twice with the same result. I tried with port 3000 and with port 7654 in case there was some silent error for a conflict with port 3000.

In both cases, the install appeared to complete successfully. The in-browser wizard worked just fine. After that was complete, I couldn't connect.

nginx error log shows this:
```
2017/04/11 20:44:52 [error] 27727#0: *68526 connect() failed (111: Connection refused) while connecting to upstream, client: 68.52.44.185, server: wiki.domain.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:7654/", host: "wiki.domain.com"
```

I checked and saw that no application was bound to port 7654. The same was true of port 3000 the first time around. I've attempted `node wiki restart` and `node wiki stop && node wiki start`. While those seem to be successful, there is still no server listening on port 7654 or 3000.

What can I do?

**Comment by NGPixel** [comment]
Do you have any errors in the /logs folder (located at the root of the wiki.js folder)

**Comment by mkunkel** [comment]
@NGPixel this error appears several times:

```
Error: Cannot find module '/var/www/wiki.nashvillerollergirls.com/node_modules/wiki.js/node_modules/pm2/lib/ProcessContainerFork.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

I checked and this error does not get thrown during `node wiki restart`

**Comment by NGPixel** [comment]
`node wiki restart` is not a valid command, it doesn't do anything.

From `/var/www/wiki.nashvillerollergirls.com`, try running the command: `node server`, wait for the server to start and paste the full output here.

**Comment by mkunkel** [comment]
That does show an error

```
2017-04-12T14:42:06.852Z - info: [SERVER] Wiki.js is initializing...
2017-04-12T14:42:07.385Z - info: [SERVER.Local] Checking data directories...
2017-04-12T14:42:07.387Z - info: [SERVER.Local] Data and Repository directories are OK.
2017-04-12T14:42:08.155Z - info: [SERVER.Git] Checking Git repository...
/var/www/wiki.domain.com/node_modules/markdown-it-anchor/index.js:34
  state.tokens[idx + 1].children[position[opts.permalinkBefore]](...linkTokens)
                                                                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/wiki.domain.com/libs/markdown.js:7:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/wiki.domain.com/server.js:39:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

**Comment by NGPixel** [comment]
ok, now I have a good idea of what the issue is. What's the version of Node you're using?

**Comment by mkunkel** [comment]
v4.7.2

**Comment by NGPixel** [comment]
Upgrade to Node v6.10.2

I'll see if I can get this fixed for v4, but upgrading will fix your issue.

**Comment by mkunkel** [comment]
That worked. `node server` starts properly, and listens on port 7654. However, `node wiki start` does not listen on 7654. Is it acceptable to use `node server` to run in production?

**Comment by NGPixel** [comment]
You can use `node server` in production. However you'll loose the following functionalities:
- Logging to /logs folder
- Background process management
- No automatic restart on crash or reboot

`node wiki start` actually calls `node server` so there's no reason it shouldn't work. Did you kill the `node server` process before trying `node wiki start`? Do you have any errors in the /logs files?

**Comment by mkunkel** [comment]
No errors, no. I needed to restart the server and everything seems to be working now. I guess we can close this since I can no longer reproduce.

Thanks for your help!
