### ISSUE TITLE
wiki.js configuration error

### ISSUE THREAD

**Issue by raghuvaidya** [Requarks/wiki#661]
Hi,
I am trying to configure wiki.js on Windows 10 PC but I get below error when I am executing node wiki configure command

C:\wiki>node wiki configure
RangeError: Maximum call stack size exceeded
    at nullCheck (internal/fs/utils.js:188:19)
    at validatePath (internal/fs/utils.js:448:11)
    at Object.mkdirSync (fs.js:742:3)
    at sync (C:\wiki\node_modules\mkdirp\index.js:71:13)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
RangeError: Maximum call stack size exceeded
    at Object.resolve (path.js:138:28)
    at Object.toNamespacedPath (path.js:623:32)
    at Object.mkdirSync (fs.js:747:28)
    at sync (C:\wiki\node_modules\mkdirp\index.js:71:13)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)

    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at Object.openSync (fs.js:436:3)
    at module.exports.Client.initFileStructure (C:\wiki\node_modules\pm2\lib\Client.js:144:10)
    at new module.exports (C:\wiki\node_modules\pm2\lib\API.js:98:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Object.<anonymous> (C:\wiki\server\init.js:5:34)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.resolve (path.js:138:28)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)
    at sync (C:\wiki\node_modules\mkdirp\index.js:77:24)

**Comment by NGPixel** [comment]
Seems like a permission issue. Try to run it from an elevated prompt.
