### ISSUE TITLE
Cannot log in after docker install

### ISSUE THREAD

**Issue by MicleBrick** [Requarks/wiki#752]
### Actual behavior
I sign in, it says it's right, says redirecting, then redirects me to the login page not signed in.

### Expected behavior
It should continue the setup

### Steps to reproduce the behavior
1. run the docker image with sqlite storage
2. go to the site
3. create account
4. try signing in

**Comment by raphaelriehl** [comment]
I have the same issue with classic install of beta 11 in Debian 9. In my case, i use MariaDB, with last update of MariaDB for respect all software requirements.

PS: I post for the first time in your projet and I wanted to thank you for your excellent work on this application !

**Comment by mjhca** [comment]
Same issue here.  Brand new install.  Details:

- MariaDB 10.3.12
- Node v11.9.0
- Redis 4.09

Setup appears to go normally but then you are stuck in a login loop.

**Comment by drsimmo** [comment]
I too have this issue in docker. I can only get the 2.0.0-beta 11 to run with the set up outlined in the example docker-compose.yml file. If I change db to anything else it produces the same results as the OP.

**Comment by NGPixel** [comment]
Was able to replicate using MariaDB.

**Comment by Liandriz** [comment]
Same with this setup, no Docker : 
  
* Alpine Linux 3.9.0,
* MariaDB 10.3.12,
* Node 10.14.2,
* Redis 4.0.12.

**Comment by NGPixel** [comment]
Fixed by b1dd54768f4eaa1422c811fd005df30cde1be9af
To be release in the upcoming beta.

**Comment by MicleBrick** [comment]
Is there a way to get the fix early?

**Comment by raphaelriehl** [comment]
I'm also interested, but on the February 4 Twitter account: "Next Wiki.js 2.0 beta, coming later this week, will include full Git integration, delete page functionality, code injection (CSS/JS) and several bug fixes. Stay tuned!"
I think we must just wait a little.

**Comment by mmajko** [comment]
Confirming this issue with SQLite. Disappeared after switching to Postgres.

**Comment by brandoncurtis** [comment]
Confirming this issue with SQLite in beta.11 and beta.42.

Here are the logs:
```
$ node server                                                                                                                                                                    
Loading configuration from /home/brandon/repo/wikijs-v2/config.yml... OK
2019-02-18T04:19:19.177Z [MASTER] info: =======================================
2019-02-18T04:19:19.184Z [MASTER] info: = Wiki.js 2.0.0-beta ==================
2019-02-18T04:19:19.184Z [MASTER] info: =======================================
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
migration file "2.0.0-beta.11.js" failed
migration failed with error: Method implemented in the dialect driver
(node:19656) UnhandledPromiseRejectionWarning: Error: Method implemented in the dialect driver
    at TableCompiler_SQLite3.TableCompiler.dropUnique.TableCompiler.dropForeign (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/tablecompiler.js:244:9)
    at TableCompiler_SQLite3.TableCompiler.alterTable (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/tablecompiler.js:199:30)
    at TableCompiler_SQLite3.TableCompiler.alter (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/tablecompiler.js:84:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/tablecompiler.js:38:20)
    at TableBuilder.toSQL (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/tablebuilder.js:49:42)
    at SchemaCompiler_SQLite3.alterTable (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/compiler.js:69:25)
    at SchemaCompiler_SQLite3.toSQL (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/compiler.js:50:26)
    at SchemaBuilder.toSQL (/home/brandon/repo/wikijs-v2/node_modules/knex/lib/schema/builder.js:68:43)
    at /home/brandon/repo/wikijs-v2/node_modules/knex/lib/runner.js:37:34
    at tryCatcher (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/util.js:16:23)
    at /home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/brandon/repo/wikijs-v2/node_modules/bluebird/js/release/promise.js:694:18)
(node:19656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handl
ed with .catch(). (rejection id: 1)
(node:19656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by NGPixel** [comment]
@brandoncurtis See #762
