### ISSUE TITLE
Cannot Find Node Module 'custom-error-instance'

### ISSUE THREAD

**Issue by dragonprevost** [Requarks/wiki#765]
I am not sure if it is expected for the user to install node packages or not. It appears one may be missing.

### Actual behavior
When runnning `node server`
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'custom-error-instance'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/wikijs/wiki/server/helpers/error.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
### Expected behavior
Expecting command to run setup server.

### Solution
`npm install` resolved the issue.

### Steps to reproduce the behavior
Follow Linux installation instruction found [here](https://docs-beta.requarks.io/install) on a fresh install of ubuntu 18.04. Using wget to download release

**Comment by NGPixel** [comment]
How did you download the package listed in the instructions? It wasn't published until just a few minutes ago...

**Comment by dragonprevost** [comment]
I downloaded the release using wget from the releases page [here](https://github.com/Requarks/wiki/releases) on github.

**Comment by NGPixel** [comment]
The archive contains a folder at `node_modules/custom-error-instance`. Make sure this folder is present in the extracted location.
