### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number

### ISSUE THREAD

**Issue by ahkimkoo** [Requarks/wiki#818]
>node server 
Loading configuration from /home/project/test/wikijs/wiki/config.yml... OK
2019-04-26T02:08:17.577Z [MASTER] info: =======================================
2019-04-26T02:08:17.578Z [MASTER] info: = Wiki.js 2.0.0-beta ==================
2019-04-26T02:08:17.579Z [MASTER] info: =======================================
internal/crypto/hash.js:58
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number
    at Hash.update (internal/crypto/hash.js:58:11)
    at sha1 (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/auth_41.js:31:8)
    at Object.token [as calculateToken] (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/auth_41.js:65:18)
    at new HandshakeResponse (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/packets/handshake_response.js:28:26)
    at ClientHandshake.sendCredentials (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/commands/client_handshake.js:51:31)
    at ClientHandshake.handshakeInit (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/commands/client_handshake.js:137:12)
    at ClientHandshake.execute (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/project/test/wikijs/wiki/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by NGPixel** [comment]
Which beta build version?
MySQL or MariaDB? Which version?

**Comment by xujiajiadexiaokeai** [comment]
i also have this problem,maybe you didn't use " ' " in your db.pass in config.yml.After i add it,the problem has fixed
wiki.js: 2.0.0-beta.84
mysql: 8.0.16

**Comment by tomnyson** [comment]
please check password should use string , I have same prolem

**Comment by mbandaNixon** [comment]
Also supplie of empty `password` field brought me to this error
