### ISSUE TITLE
Windows Installation cant start server, missing sqlite3

### ISSUE THREAD

**Issue by aalmir** [Requarks/wiki#870]
**Describe the bug**
Some errors during Windows installation:
Powershell:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12     <-- needed before
Invoke-WebRequest -Uri "https://github.com/Requarks/wiki/releases/download/2.0.0-beta.180/wiki-js.tar.gz" -OutFile "wiki-js.tar.gz"
for downloading, see --> https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**To Reproduce**
before node server
i tryed 
npm install and 
npm install sqlite3 --save
but still this error:

Knex: run
$ npm install sqlite3 --save
Cannot find module 'C:\wiki\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node'
Error: Cannot find module 'C:\wiki\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\wiki\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Client_SQLite3._driver (C:\wiki\node_modules\knex\lib\dialects\sqlite3\index.js:46:12)
    at Client_SQLite3.initializeDriver (C:\wiki\node_modules\knex\lib\client.js:253:26)
    at Client_SQLite3.Client (C:\wiki\node_modules\knex\lib\client.js:84:10)
    at new Client_SQLite3 (C:\wiki\node_modules\knex\lib\dialects\sqlite3\index.js:33:19)
(node:3596) UnhandledPromiseRejectionWarning: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'C:\wiki\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node'
    at Client_SQLite3.initializeDriver (C:\wiki\node_modules\knex\lib\client.js:257:13)
    at Client_SQLite3.Client (C:\wiki\node_modules\knex\lib\client.js:84:10)
    at new Client_SQLite3 (C:\wiki\node_modules\knex\lib\dialects\sqlite3\index.js:33:19)
    at Knex (C:\wiki\node_modules\knex\lib\knex.js:57:42)
    at Object.init (C:\wiki\server\core\db.js:81:17)
    at Object.init (C:\wiki\server\core\kernel.js:13:35)
    at Object.<anonymous> (C:\wiki\server\index.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:3596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Expected behavior**
a running system

**Screenshots**
no images

**Host Info (please complete the following information):**
 - OS: Win10
 - Wiki.js version: 2.0.0-beta.180
 - Database engine: sqlite

**Additional context**
nothing

**Comment by NGPixel** [comment]
This has been fixed for the upcoming beta build.
