### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by rickywu** [Requarks/wiki#878]
I got beta 180 version and run these command:

npm install
make build:

```
Hash: bca7689fcd14d560855f
Version: webpack 4.32.2
Time: 20464ms
Built at: 06/13/2019 10:53:15 AM
 9 assets
[./client/client-app.js] 262 bytes {app} [built] [failed] [1 error]
    [./client/index-app.js] 102ms -> factory:9197ms building:71ms dependencies:1557ms = 10927ms
[./client/client-setup.js] 259 bytes {setup} [built] [failed] [1 error]
    [./client/index-setup.js] 84ms -> factory:427ms building:8ms dependencies:267ms = 786ms
[./client/helpers/compatibility.js] 205 bytes {app} {setup} [built]
    [./client/index-setup.js] 84ms -> factory:427ms building:8ms dependencies:267ms = 786ms
[./client/index-app.js] 9.31 KiB {app} [built]
    factory:76ms building:26ms dependencies:669ms = 771ms
[./client/index-setup.js] 169 bytes {setup} [built]
    factory:81ms building:3ms = 84ms
[./client/scss/app.scss] 1.72 KiB {app} {setup} [built]
    [./client/index-setup.js] 84ms -> factory:427ms building:8ms dependencies:267ms = 786ms
[./client/themes/default/js/app.js] 31 bytes {app} [built]
    [./client/index-app.js] 102ms -> factory:9197ms building:71ms dependencies:1557ms = 10927ms
[./client/themes/default/scss/app.scss] 1.82 KiB {app} [built]
    [./client/index-app.js] 102ms -> factory:9197ms building:71ms dependencies:1557ms = 10927ms
[./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src/index.js!./node_modules/sass-loader/lib/loader.js?!./node_modules/sass-resources-loader/lib/loader.js?!./client/scss/app.scss] ./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js??ref--2-5!./node_modules/sass-resources-loader/lib/loader.js??ref--2-6!./client/scss/app.scss 39 bytes {app} {setup} [built]
    [./client/index-setup.js] 84ms -> [./client/scss/app.scss] 435ms -> factory:267ms building:13414ms = 14200ms
[./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src/index.js!./node_modules/sass-loader/lib/loader.js?!./node_modules/sass-resources-loader/lib/loader.js?!./client/themes/default/scss/app.scss] ./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js??ref--2-5!./node_modules/sass-resources-loader/lib/loader.js??ref--2-6!./client/themes/default/scss/app.scss 39 bytes {app} [built]
    [./client/index-app.js] 102ms -> [./client/themes/default/scss/app.scss] 9268ms -> factory:7ms building:4420ms = 13797ms
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {app} [built]
    [./client/index-app.js] 102ms -> [./node_modules/core-js/modules/es.json.to-string-tag.js] 9268ms -> [./node_modules/core-js/internals/global.js] 307ms -> factory:917ms building:7385ms = 17979ms
    + 669 hidden modules

ERROR in ./client/client-setup.js 15:9
Module parse failed: Unexpected token (15:9)
You may need an appropriate loader to handle this file type.
| });
| Vue.component('setup', function () {
>   return import(
|   /* webpackMode: "eager" */
|   './components/setup.vue');
 @ ./client/index-setup.js 9:0-28

ERROR in ./client/client-app.js 193:9
Module parse failed: Unexpected token (193:9)
You may need an appropriate loader to handle this file type.
|
| Vue.component('admin', function () {
>   return import(
|   /* webpackChunkName: "admin" */
|   './components/admin.vue');
 @ ./client/index-app.js 213:0-26
make: *** [build] Error 2
```

yarn run dev:
```
2019-06-13T02:54:52.130Z [MASTER] error: ENOENT: no such file or directory, stat '/root/wiki-2.0.0-beta.180/assets/favicon.ico'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NGPixel** [comment]
Which version of Node.js?
Which OS and version?

**Comment by rickywu** [comment]
Tried two env, 1st is CentOS
---
CentOS Linux release 7.5.1804 (Core)
node v10.16.0
npm 6.9.0

2nd is WSL
---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
node v10.15.1
npm 6.4.1

**Comment by rickywu** [comment]
This is caused by npm install problem, I tried in cloud env install again and make build sucessfully but got new problem:

node wiki start
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/wiki/wiki'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
make: *** [start] Error 1

**Comment by comran** [comment]
@rickywu I was having the same issue. It's something to do with webpack / acorn dependencies.

This fixed my issue:
https://github.com/webpack/webpack/issues/8656#issuecomment-499150562

@NGPixel here are my versions:
`{ wiki: '2.0.0-beta',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.34.0',
  node: '10.16.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.52',
  zlib: '1.2.11' }`

**Comment by rickywu** [comment]
@comran Yes, I was lucky install webpack and follow https://github.com/Requarks/wiki/issues/838 
solve this problem
