### ISSUE TITLE
Fresh install of 2.0.0-beta.267 crashes

### ISSUE THREAD

**Issue by hellfirehd** [Requarks/wiki#981]
**Describe the bug**
The install and setup seem to go fine.  Then after first login a blank page is shown and the following error is observed in the browser console:
```
ReferenceError: "en is not defined"
    anonymous https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js line 89 > Function:3
    _render https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    i https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    get https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    vn https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    $mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    $mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    _init https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    Ln https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    js https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:2
app.a15b0f9903dda3fec2a6.js:89:11689
    Wt https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    Ut https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    zt https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    _render https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    i https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    get https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    vn https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    $mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    $mount https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    _init https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    Ln https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:89
    js https://wiki.dkw.io/js/app.a15b0f9903dda3fec2a6.js:2
```

**To Reproduce**
1. `docker-compose.yml`
```
version: "3"

networks:
  dkw:
    driver: bridge

services:

  wikijsdb:
    image: postgres:9-alpine
    container_name: wikijsdb
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ******
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /docker/wiki/data:/var/lib/postgresql/data
    networks:
      - dkw

  wikijs:
    image: requarks/wiki:beta
    container_name: wikijs
    depends_on:
      - wikijsdb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijsdb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ******
      DB_NAME: wiki
    networks:
      - dkw
    ports:
      - "6000:3000"
```
2. `docker-compose up -d`
3. Browse to the URL
4. Set admin email and password
5. Login
6. See the error

**Expected behavior**
See the first page after login.

**Host Info (please complete the following information):**
 - Browser: Firefox 68.0.2
 - OS: CentOS 7
 - Docker: 18.09.7, build 2d0083d
 - Wiki.js version: 2.0.0-beta.267
 - Database engine: postgres:9-alpine

`docker logs wikijs`
```syslog
Loading configuration from /wiki/config.yml... OK
2019-08-25T19:17:51.297Z [MASTER] info: =======================================
2019-08-25T19:17:51.302Z [MASTER] info: = Wiki.js 2.0.0-beta.267 ==============
2019-08-25T19:17:51.303Z [MASTER] info: =======================================
2019-08-25T19:17:51.303Z [MASTER] info: Initializing...
2019-08-25T19:17:52.233Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-08-25T19:17:52.234Z [MASTER] info: Starting setup wizard...
2019-08-25T19:17:52.703Z [MASTER] info: Starting HTTP server on port 3000...
2019-08-25T19:17:52.703Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-08-25T19:17:52.726Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-08-25T19:17:52.726Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-08-25T19:17:52.726Z [MASTER] info:
2019-08-25T19:17:52.727Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-08-25T19:17:52.727Z [MASTER] info:
2019-08-25T19:17:52.727Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
2019-08-25T19:18:26.164Z [MASTER] info: Creating data directories...
2019-08-25T19:18:26.220Z [MASTER] info: Generating certificates...
2019-08-25T19:18:26.354Z [MASTER] info: Persisting config to DB...
2019-08-25T19:18:26.724Z [MASTER] info: Installing default locale...
2019-08-25T19:18:26.745Z [MASTER] info: Creating default groups...
2019-08-25T19:18:26.958Z [MASTER] info: Loaded 19 new authentication strategies: [ OK ]
2019-08-25T19:18:26.997Z [MASTER] info: Loaded 2 new editors: [ OK ]
2019-08-25T19:18:27.099Z [MASTER] info: Loaded 12 new loggers: [ OK ]
2019-08-25T19:18:27.204Z [MASTER] info: Loaded 19 new renderers: [ OK ]
2019-08-25T19:18:27.275Z [MASTER] info: Loaded 9 new search engines: [ OK ]
2019-08-25T19:18:27.360Z [MASTER] info: Loaded 10 new storage targets: [ OK ]
2019-08-25T19:18:27.360Z [MASTER] info: Creating root administrator...
2019-08-25T19:18:28.224Z [MASTER] info: Creating guest account...
2019-08-25T19:18:28.232Z [MASTER] info: Creating default site navigation
2019-08-25T19:18:28.241Z [MASTER] info: Setup is complete!
2019-08-25T19:18:28.242Z [MASTER] info: Stopping Setup...
2019-08-25T19:18:28.244Z [MASTER] info: Setup stopped. Starting Wiki.js...
2019-08-25T19:18:30.138Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
2019-08-25T19:18:30.325Z [MASTER] info: Loading GraphQL Schema...
2019-08-25T19:18:30.811Z [MASTER] info: GraphQL Schema: [ OK ]
2019-08-25T19:18:31.180Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-08-25T19:18:31.202Z [MASTER] info: HTTP Server: [ RUNNING ]
TypeError: /wiki/server/views/master.pug:2
    1| doctype html
  > 2| html(lang=siteConfig.lang)
    3|   head
    4|     meta(http-equiv='X-UA-Compatible', content='IE=edge')
    5|     meta(charset='UTF-8')

Cannot read property 'lang' of undefined
    at eval (eval at wrap (/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6:67)
    at template (eval at wrap (/wiki/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:151:139)
    at Object.exports.renderFile (/wiki/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/wiki/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/wiki/node_modules/pug/lib/index.js:464:11)
    at View.render (/wiki/node_modules/express/lib/view.js:135:8)
    at tryRender (/wiki/node_modules/express/lib/application.js:640:10)
    at Function.render (/wiki/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/wiki/node_modules/express/lib/response.js:1012:7)
    at app.use (/wiki/server/master.js:178:9)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
    at /wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
    at /wiki/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/wiki/node_modules/express/lib/router/index.js:335:12)
    at next (/wiki/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/wiki/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/wiki/node_modules/express/lib/router/index.js:315:13)
2019-08-25T19:18:31.454Z [MASTER] info: Loaded 12 new analytics providers: [ OK ]
2019-08-25T19:18:31.523Z [MASTER] info: No new authentication strategies found: [ SKIPPED ]
2019-08-25T19:18:31.531Z [MASTER] info: No new editors found: [ SKIPPED ]
2019-08-25T19:18:31.577Z [MASTER] info: No new loggers found: [ SKIPPED ]
2019-08-25T19:18:31.652Z [MASTER] info: No new renderers found: [ SKIPPED ]
2019-08-25T19:18:31.682Z [MASTER] info: No new search engines found: [ SKIPPED ]
2019-08-25T19:18:31.716Z [MASTER] info: No new storage targets found: [ SKIPPED ]
2019-08-25T19:18:31.722Z [MASTER] info: Authentication Strategy local: [ OK ]
2019-08-25T19:18:31.729Z [MASTER] info: Purging orphaned upload files...
2019-08-25T19:18:31.738Z [MASTER] info: Syncing locales with Graph endpoint...
2019-08-25T19:18:31.740Z [MASTER] info: Fetching latest updates from Graph endpoint...
2019-08-25T19:18:31.746Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
2019-08-25T19:18:32.289Z [MASTER] info: Fetching latest updates from Graph endpoint: [ COMPLETED ]
2019-08-25T19:18:32.294Z [MASTER] info: Pulled latest locale updates for English from Graph endpoint: [ COMPLETED ]
2019-08-25T19:18:32.304Z [MASTER] info: Syncing locales with Graph endpoint: [ COMPLETED ]
```

**Comment by NGPixel** [comment]
Fixed by 1419e9613a2f0cfc159dbeea6174d9e221ea93ec.

A new release is building right now and will be released shortly.
